#!/usr/bin/env bash
# WrenAI main-line (open-core) for the TİMAŞ cockpit:
#   project  : $PROJECT (generated by tools/wren/legacy_to_project.py from the legacy wren-ui deployment)
#   engine   : `wrenai` package in $VENV (in-process DataFusion/MDL engine, SQL Server connector)
#   service  : backend/wren_bridge (FastAPI :8794) — cockpit contract (/api/v1/run_sql, /api/v1/ask) on the new engine
# Steps: connection file from secrets → context validate/build → memory index → query smoke → unit → health → ask smoke.
set -euo pipefail
export SYSTEMD_BUS_TIMEOUT="${SYSTEMD_BUS_TIMEOUT:-300}"
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
VENV="${WREN_VENV:-/data/nanobaseai/bi/wren-venv}"
PROJECT="${WREN_PROJECT:-/data/nanobaseai/bi/wren-project/logo_timas}"
SECRETS="${SECRETS_ROOT:-/data/nanobaseai/bi/secrets}"
CONN_FILE="${WREN_CONNECTION_FILE:-${SECRETS}/wren-logo-connection.json}"
API_ENV="${NANOBASE_API_ENV:-/data/nanobaseai/bi/frontend/backend/nanobase_api.env}"
ENV_FILE="${WREN_BRIDGE_ENV:-/data/nanobaseai/bi/frontend/backend/nanobase_wren_bridge.env}"
UNIT=/etc/systemd/system/nanobase-wren-bridge.service
PORT="${WREN_BRIDGE_PORT:-8794}"
WORKERS="${WREN_BRIDGE_WORKERS:-3}"   # işçi başına ayrı engine → paralel sorgu; RAM ~1.5 GB/işçi
WREN="${VENV}/bin/wren"

log() { printf '[deploy-wren-bridge] %s\n' "$*"; }
die() { printf '[deploy-wren-bridge] ERROR: %s\n' "$*" >&2; exit 1; }

[[ -x "$WREN" ]] || die "missing $WREN — pip install 'wrenai[mssql,memory]' into $VENV first"
[[ -f "${PROJECT}/wren_project.yml" ]] || die "missing project ${PROJECT} (run tools/wren/legacy_to_project.py)"
log "wrenai $("$WREN" --version 2>/dev/null | head -1)"

# --- 0. FreeTDS compatibility shim (see tools/wren/sitecustomize.py) ----------------------------
# Installed as a .pth-triggered module: Ubuntu's /usr/lib/python3.12/sitecustomize.py shadows a venv sitecustomize.
SITE="$("${VENV}/bin/python" -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])')"
rm -f "${SITE}/sitecustomize.py"
cp "${ROOT}/tools/wren/sitecustomize.py" "${SITE}/nanobaseai_odbc_shim.py"
echo "import nanobaseai_odbc_shim" > "${SITE}/nanobaseai_odbc_shim.pth"
"${VENV}/bin/python" -c 'import wren.connector.mssql as m; assert getattr(m, "_NANOBASEAI_ODBC_SHIM", False), "shim not active"; print("  odbc shim active")'

# --- 1. connection file (never printed) from the registered MSSQL datasource --------------------
if [[ ! -f "$CONN_FILE" ]]; then
  log "writing connection file ${CONN_FILE} from ${SECRETS}/mssql-ro.datasources.json"
  umask 077
  python3 - "$SECRETS" "$CONN_FILE" <<'PY'
import json, sys, pathlib
secrets, out = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
reg = json.loads((secrets / "mssql-ro.datasources.json").read_text())
src = reg["sources"]["logo"]
pw_file = src.get("password_file") or str(secrets / "mssql-logo.password")
pw = pathlib.Path(pw_file if pw_file.startswith("/") else str(secrets / pw_file)).read_text().strip()
# FreeTDS ODBC driver (apt unixodbc + tdsodbc, no EULA) — same TDS path the legacy ibis-freetds image used.
conn = {"datasource": "mssql", "host": src["host"], "port": str(src["port"]), "database": src["database"], "user": src["user"], "password": pw,
        "driver": "FreeTDS", "tds_version": "7.4", "kwargs": {"ClientCharset": "UTF-8"}}
out.write_text(json.dumps(conn))
print("connection fields:", [k for k in conn if k != "password"])
PY
  chmod 600 "$CONN_FILE"
fi
log "connector field reference: $("$WREN" docs connection-info mssql 2>/dev/null | tr '\n' ' ' | cut -c1-300)"

# --- 2. build MDL + memory index ---------------------------------------------------------------
cd "$PROJECT"
log "context validate"; "$WREN" context validate
log "context build";    "$WREN" context build
[[ -f target/mdl.json ]] || die "target/mdl.json not produced"
python3 -c "import json; m=json.load(open('target/mdl.json')); print('  models', len(m['models']), 'columns', sum(len(x['columns']) for x in m['models']), 'relationships', len(m.get('relationships', [])))"
log "memory index (schema + knowledge/)"
"$WREN" memory index --mdl target/mdl.json 2>&1 | tail -3 || log "WARN: memory index failed — recall falls back to token search"

# --- 3. engine smoke: the cockpit's summary query -----------------------------------------------
log "query smoke (2026 sales/returns/purchases from INVOICE)"
"$WREN" query --mdl target/mdl.json --connection-file "$CONN_FILE" --output json --sql '
SELECT
  SUM(CASE WHEN "TRCODE" IN (7,8,9) THEN "NETTOTAL" ELSE 0 END) AS sales,
  SUM(CASE WHEN "TRCODE" IN (2,3)   THEN "NETTOTAL" ELSE 0 END) AS returns,
  SUM(CASE WHEN "TRCODE" IN (1,4)   THEN "NETTOTAL" ELSE 0 END) AS purchases,
  SUM(CASE WHEN "TRCODE" IN (7,8,9) THEN 1 ELSE 0 END)          AS invoices,
  MAX("DATE_") AS last_date
FROM "dbo_LG_411_01_INVOICE"
WHERE "CANCELLED" = 0' | head -c 600; echo

# --- 4. bridge service -----------------------------------------------------------------------
log "installing bridge deps into ${VENV}"
"${VENV}/bin/python" -m pip install -q -r "${ROOT}/backend/wren_bridge/requirements.txt"
LLM_BASE="$(grep -E '^OPENAI_API_BASE=' "$API_ENV" | cut -d= -f2- | tr -d '"')"
LLM_KEY="$(grep -E '^OPENAI_API_KEY=' "$API_ENV" | cut -d= -f2- | tr -d '"')"
LLM_MODEL="$(grep -E '^LLM_MODEL_NAME=' "$API_ENV" | cut -d= -f2- | tr -d '"')"
umask 077
cat > "$ENV_FILE" <<ENV
# NanobaseAI BI — Wren bridge (generated by scripts/server/deploy-wren-bridge.sh)
WREN_PROJECT=${PROJECT}
WREN_CONNECTION_FILE=${CONN_FILE}
OPENAI_API_BASE=${LLM_BASE:-http://172.17.0.1:8020/v1}
OPENAI_API_KEY=${LLM_KEY}
LLM_MODEL_NAME=${LLM_MODEL:-nanobaseai-bi-llm}
LLM_TIMEOUT_SEC=240
WREN_MAX_ROWS=500
WREN_CONTEXT_ITEMS=40
WREN_RECALL_LIMIT=4
WREN_CACHE_TTL_SEC=300
REDIS_URL=redis://127.0.0.1:6379/2
WREN_CACHE_MAX=256
HF_HUB_OFFLINE=0
ENV
chmod 600 "$ENV_FILE"
sudo -E tee "$UNIT" >/dev/null <<UNIT
[Unit]
Description=NanobaseAI BI Wren bridge (WrenAI core engine + LLM orchestration, :${PORT})
After=network.target

[Service]
Type=simple
User=administrator
WorkingDirectory=${ROOT}/backend
EnvironmentFile=${ENV_FILE}
Environment=PATH=${VENV}/bin:/usr/bin
Environment=PYTHONPATH=${ROOT}/backend
ExecStart=${VENV}/bin/uvicorn wren_bridge.app:app --host 127.0.0.1 --port ${PORT} --workers ${WORKERS} --timeout-keep-alive 30
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
UNIT
sudo -E systemctl daemon-reload || log "WARN: daemon-reload timed out (busy host) — continuing"
sudo -E systemctl enable nanobase-wren-bridge >/dev/null 2>&1 || true
sudo -E systemctl restart nanobase-wren-bridge
for i in $(seq 1 60); do curl -fsS "http://127.0.0.1:${PORT}/health" >/dev/null 2>&1 && break; sleep 2; done
curl -fsS "http://127.0.0.1:${PORT}/health" | python3 -m json.tool
curl -fsS "http://127.0.0.1:${PORT}/api/v1/engine" | python3 -m json.tool
log "run_sql smoke via bridge"
curl -fsS -X POST "http://127.0.0.1:${PORT}/api/v1/run_sql" -H 'Content-Type: application/json' \
  -d '{"sql":"SELECT TOP 3 \"LOGICALREF\", \"DATE_\", \"NETTOTAL\" FROM \"dbo_LG_411_01_INVOICE\" WHERE \"CANCELLED\" = 0 ORDER BY \"DATE_\" DESC","limit":3}' | head -c 400; echo
log "nanobase-wren-bridge active on :${PORT}"
