#!/usr/bin/env bash
# Install + systemd for the NanobaseAI BI Forecast API (:8793) running TimesFM 3.0.
#
# Prerequisites on the host (done once, outside this script):
#   * upstream clone https://github.com/google-research/timesfm  → $TIMESFM_SRC
#   * venv with `pip install -e $TIMESFM_SRC` (timesfm 3.0.x) + CPU torch  → $VENV
#   * checkpoint google/timesfm-3.0-pytorch downloaded to $MODEL_DIR (config + safetensors)
# The script installs the service requirements into that venv, writes the env
# file + unit, restarts the service and waits for /health to report ready.
set -euo pipefail
# Shared host: systemd's manager can take >25 s to answer; keep systemctl from timing out.
export SYSTEMD_BUS_TIMEOUT="${SYSTEMD_BUS_TIMEOUT:-300}"

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
VENV="${FORECAST_VENV:-/data/nanobaseai/bi/timesfm-venv}"
TIMESFM_SRC="${TIMESFM_SRC:-/data/nanobaseai/bi/timesfm}"
MODEL_DIR="${FORECAST_MODEL3_DIR:-/data/nanobaseai/bi/models/timesfm-3.0-pytorch}"
ENV_FILE="${FORECAST_ENV_FILE:-/data/nanobaseai/bi/frontend/backend/nanobase_forecast.env}"
UNIT=/etc/systemd/system/nanobase-forecast.service
PORT="${FORECAST_PORT:-8793}"
THREADS="${FORECAST_THREADS:-8}"
CPU_QUOTA="${FORECAST_CPU_QUOTA:-800%}"
READY_TIMEOUT="${FORECAST_READY_TIMEOUT:-300}"

log() { printf '[deploy-forecast] %s\n' "$*"; }
die() { printf '[deploy-forecast] ERROR: %s\n' "$*" >&2; exit 1; }

[[ -x "${VENV}/bin/python" ]] || die "missing venv ${VENV}"
[[ -d "${ROOT}/backend/forecasting" ]] || die "missing ${ROOT}/backend/forecasting (rsync the repo first)"
[[ -d "${MODEL_DIR}" ]] || die "missing checkpoint dir ${MODEL_DIR}"
ls "${MODEL_DIR}"/*.safetensors >/dev/null 2>&1 || die "no *.safetensors in ${MODEL_DIR}"

log "TimesFM package check"
"${VENV}/bin/python" - <<'PY' || die "timesfm3 import failed in venv — install the upstream repo: pip install -e ${TIMESFM_SRC}"
import importlib.metadata as md
import timesfm3  # noqa: F401
from timesfm3 import ModelConfig, TimesFM3Evaluator  # noqa: F401
print("timesfm", md.version("timesfm"))
PY
if [[ -d "${TIMESFM_SRC}/.git" ]]; then
  log "upstream timesfm commit: $(git -C "${TIMESFM_SRC}" rev-parse --short HEAD)"
fi

log "Installing service deps into ${VENV}"
"${VENV}/bin/python" -m pip install -q -r "${ROOT}/backend/forecasting/requirements.txt"

umask 077
cat > "${ENV_FILE}" <<ENV
# NanobaseAI BI Forecast API — generated by scripts/server/deploy-forecast.sh
FORECAST_ENGINE=timesfm3
FORECAST_MODEL3_ID=${MODEL_DIR}
# TimesFM 3.0 weights: non-commercial upstream licence, use decided by the operator.
FORECAST_ALLOW_NONCOMMERCIAL=1
FORECAST_DEVICE=cpu
FORECAST_THREADS=${THREADS}
FORECAST_BATCH=1
FORECAST_SYMMETRIC_AVERAGING=0
FORECAST_WARM=1
FORECAST_CACHE_MAX=512
HF_HUB_OFFLINE=1
TOKENIZERS_PARALLELISM=false
ENV
chmod 600 "${ENV_FILE}"

sudo tee "${UNIT}" >/dev/null <<UNIT
[Unit]
Description=NanobaseAI BI Forecast API (TimesFM 3.0, :${PORT})
After=network.target

[Service]
Type=simple
User=administrator
WorkingDirectory=${ROOT}/backend
EnvironmentFile=${ENV_FILE}
Environment=PATH=${VENV}/bin:/usr/bin
Environment=PYTHONPATH=${ROOT}/backend
ExecStart=${VENV}/bin/uvicorn forecasting.app.main:app --host 127.0.0.1 --port ${PORT} --workers 1 --timeout-keep-alive 30
Restart=on-failure
RestartSec=5
# Shared host: cap the CPU share of torch inference.
CPUQuota=${CPU_QUOTA}

[Install]
WantedBy=multi-user.target
UNIT

sudo -E systemctl daemon-reload
sudo -E systemctl enable nanobase-forecast >/dev/null
sudo -E systemctl restart nanobase-forecast

log "Waiting for /health ready (timeout ${READY_TIMEOUT}s — first start hashes + loads the checkpoint)"
deadline=$(( $(date +%s) + READY_TIMEOUT ))
while :; do
  if body="$(curl -fsS "http://127.0.0.1:${PORT}/health" 2>/dev/null)"; then
    echo "$body" | python3 -m json.tool
    break
  fi
  if (( $(date +%s) > deadline )); then
    curl -sS "http://127.0.0.1:${PORT}/health" || true
    sudo -E journalctl -u nanobase-forecast -n 40 --no-pager
    die "forecast service not ready after ${READY_TIMEOUT}s"
  fi
  sleep 5
done
curl -fsS "http://127.0.0.1:${PORT}/engines" | python3 -m json.tool
log "nanobase-forecast active on :${PORT} (engine timesfm3)"
