"""Question-independent, trusted CRM physical vocabulary.

Only logical IDs are planner inputs; physical identifiers and predicates here
are reviewed constants. Metadata is not business/API acceptance. Runtime must
verify schema and apply every entity active predicate, including LEFT targets,
AND the shared passive-record rule (statecode=0, no Pasif/Inactive status reason)
on every table that has statecode (relational_executor + executor.crm_active).
"""

SCHEMA_PROVENANCE = {'crm_inventory_20260930_r2': {'artifact': 'crm-coverage/inventory-source.json',
                               'server_source': '/data/nanobaseai/bi/acceptance/finance-expanded-20260930/schema/codex-crm-full-inventory-20260930-r2.json',
                               'sha256': 'ee26a27cc48bd6fa7d5d631453d4a75025c61517705e2602ea0927e341fe9a8e',
                               'collected_at': '2026-09-30T17:57:47.814751+00:00',
                               'mapping_source': 'backend/semantic_bridge/finance_query/crm_reports.py',
                               'documentation': ['docs/reports/crm-report-schema-and-acceptance-20260930.md',
                                                 'docs/reports/crm-history-contract-evidence-20260930.md'],
                               'business_acceptance': False}}

ENTITY_REGISTRY = {'book': {'table': 'new_kitapBase',
          'schema': 'dbo',
          'primary_key': 'book_id',
          'grain': 'one physical source record',
          'fields': {'book_id': {'column': 'new_kitapId',
                                 'type': 'identity',
                                 'sql_type': 'uniqueidentifier',
                                 'nullable': False,
                                 'sum_allowed': False},
                     'book_code': {'column': 'new_StokKodu',
                                   'type': 'text',
                                   'sql_type': 'nvarchar',
                                   'nullable': True,
                                   'sum_allowed': False},
                     'book_name': {'column': 'new_name',
                                   'type': 'text',
                                   'sql_type': 'nvarchar',
                                   'nullable': True,
                                   'sum_allowed': False},
                     'isbn': {'column': 'new_isbn13',
                              'type': 'text',
                              'sql_type': 'nvarchar',
                              'nullable': True,
                              'sum_allowed': False},
                     'author_text': {'column': 'new_yazartext',
                                     'type': 'text',
                                     'sql_type': 'nvarchar',
                                     'nullable': True,
                                     'sum_allowed': False},
                     'publisher_id': {'column': 'new_yayineviid',
                                      'type': 'identity',
                                      'sql_type': 'uniqueidentifier',
                                      'nullable': True,
                                      'sum_allowed': False},
                     'subbrand_id': {'column': 'new_yayinciid',
                                     'type': 'identity',
                                     'sql_type': 'uniqueidentifier',
                                     'nullable': True,
                                     'sum_allowed': False},
                     'alternate_subbrand_id': {'column': 'new_YayneviAltMarka',
                                               'type': 'identity',
                                               'sql_type': 'uniqueidentifier',
                                               'nullable': True,
                                               'sum_allowed': False},
                     'first_print_date': {'column': 'new_ilkyayintarihi',
                                          'type': 'date',
                                          'sql_type': 'datetime',
                                          'nullable': True,
                                          'sum_allowed': False,
                                          'semantics': 'stored CRM timestamp; never infer stage entry or '
                                                       'field-change event'},
                     'last_publication_date': {'column': 'new_sonyayintarihi',
                                               'type': 'date',
                                               'sql_type': 'datetime',
                                               'nullable': True,
                                               'sum_allowed': False,
                                               'semantics': 'stored CRM timestamp; never infer stage entry '
                                                            'or field-change event'},
                     'edition_count': {'column': 'new_baskisayisi',
                                       'type': 'number',
                                       'sql_type': 'int',
                                       'nullable': True,
                                       'sum_allowed': False},
                     'last_print_date': {'column': 'new_baskitarihi',
                                         'type': 'date',
                                         'sql_type': 'datetime',
                                         'nullable': True,
                                         'sum_allowed': False,
                                         'semantics': 'stored CRM timestamp; never infer stage entry or '
                                                      'field-change event'},
                     'created_at': {'column': 'CreatedOn',
                                    'type': 'date',
                                    'sql_type': 'datetime',
                                    'nullable': True,
                                    'sum_allowed': False,
                                    'semantics': 'stored CRM timestamp; never infer stage entry or '
                                                 'field-change event'},
                     'updated_at': {'column': 'ModifiedOn',
                                    'type': 'date',
                                    'sql_type': 'datetime',
                                    'nullable': True,
                                    'sum_allowed': False,
                                    'semantics': 'stored CRM timestamp; never infer stage entry or '
                                                 'field-change event'},
                     'editor_id': {'column': 'new_Editor',
                                   'type': 'identity',
                                   'sql_type': 'uniqueidentifier',
                                   'nullable': True,
                                   'sum_allowed': False},
                     'project_editor_id': {'column': 'new_projeeditoru',
                                           'type': 'identity',
                                           'sql_type': 'uniqueidentifier',
                                           'nullable': True,
                                           'sum_allowed': False},
                     'publishing_director_id': {'column': 'new_yayinyonetmeni',
                                                'type': 'identity',
                                                'sql_type': 'uniqueidentifier',
                                                'nullable': True,
                                                'sum_allowed': False},
                     'owner_id': {'column': 'OwnerId',
                                  'type': 'identity',
                                  'sql_type': 'uniqueidentifier',
                                  'nullable': False,
                                  'sum_allowed': False},
                     'previous_publisher_id': {'column': 'new_oncekiyayineviid',
                                               'type': 'identity',
                                               'sql_type': 'uniqueidentifier',
                                               'nullable': True,
                                               'sum_allowed': False},
                     'book_project_id': {'column': 'new_KitapProjesi',
                                         'type': 'identity',
                                         'sql_type': 'uniqueidentifier',
                                         'nullable': True,
                                         'sum_allowed': False},
                     'project_card_id': {'column': 'new_projekarti',
                                         'type': 'identity',
                                         'sql_type': 'uniqueidentifier',
                                         'nullable': True,
                                         'sum_allowed': False},
                     'statecode': {'column': 'statecode',
                                   'type': 'number',
                                   'sql_type': 'int',
                                   'nullable': False,
                                   'sum_allowed': False},
                     'statuscode': {'column': 'statuscode',
                                    'type': 'number',
                                    'sql_type': 'int',
                                    'nullable': True,
                                    'sum_allowed': False}},
          'active_predicate': '{alias}.[statecode]=0 AND {alias}.[statuscode]=1',
          'predicate_columns': ['statecode', 'statuscode'],
          'provenance': 'crm_inventory_20260930_r2',
          'semantic_notes': ['publisher_id and subbrand_id reference the same entity under distinct roles, '
                             'not a hierarchy.',
                             'first_print_date means first print.',
                             'OwnerId is polymorphic, no unqualified SystemUser join.']},
 'publisher': {'table': 'new_markaBase',
               'schema': 'dbo',
               'primary_key': 'publisher_id',
               'grain': 'one physical source record',
               'fields': {'publisher_id': {'column': 'new_markaId',
                                           'type': 'identity',
                                           'sql_type': 'uniqueidentifier',
                                           'nullable': False,
                                           'sum_allowed': False},
                          'name': {'column': 'new_name',
                                   'type': 'text',
                                   'sql_type': 'nvarchar',
                                   'nullable': True,
                                   'sum_allowed': False},
                          'statecode': {'column': 'statecode',
                                        'type': 'number',
                                        'sql_type': 'int',
                                        'nullable': False,
                                        'sum_allowed': False},
                          'statuscode': {'column': 'statuscode',
                                         'type': 'number',
                                         'sql_type': 'int',
                                         'nullable': True,
                                         'sum_allowed': False}},
               'active_predicate': '{alias}.[statecode]=0 AND {alias}.[statuscode]=1',
               'predicate_columns': ['statecode', 'statuscode'],
               'provenance': 'crm_inventory_20260930_r2',
               'semantic_notes': []},
 'alternate_subbrand': {'table': 'new_yaynevialtmarkaBase',
                        'schema': 'dbo',
                        'primary_key': 'subbrand_id',
                        'grain': 'one physical source record',
                        'fields': {'subbrand_id': {'column': 'new_yaynevialtmarkaId',
                                                   'type': 'identity',
                                                   'sql_type': 'uniqueidentifier',
                                                   'nullable': False,
                                                   'sum_allowed': False},
                                   'name': {'column': 'new_name',
                                            'type': 'text',
                                            'sql_type': 'nvarchar',
                                            'nullable': True,
                                            'sum_allowed': False},
                                   'statecode': {'column': 'statecode',
                                                 'type': 'number',
                                                 'sql_type': 'int',
                                                 'nullable': False,
                                                 'sum_allowed': False},
                                   'statuscode': {'column': 'statuscode',
                                                  'type': 'number',
                                                  'sql_type': 'int',
                                                  'nullable': True,
                                                  'sum_allowed': False}},
                        'active_predicate': '{alias}.[statecode]=0',
                        'predicate_columns': ['statecode'],
                        'provenance': 'crm_inventory_20260930_r2',
                        'semantic_notes': []},
 'contact': {'table': 'ContactBase',
             'schema': 'dbo',
             'primary_key': 'person_id',
             'grain': 'one physical source record',
             'fields': {'person_id': {'column': 'ContactId',
                                      'type': 'identity',
                                      'sql_type': 'uniqueidentifier',
                                      'nullable': False,
                                      'sum_allowed': False},
                        'person_name': {'column': 'FullName',
                                        'type': 'text',
                                        'sql_type': 'nvarchar',
                                        'nullable': True,
                                        'sum_allowed': False},
                        'is_author': {'column': 'new_yazarmi',
                                      'type': 'bool',
                                      'sql_type': 'bit',
                                      'nullable': True,
                                      'sum_allowed': False},
                        'email': {'column': 'EMailAddress1',
                                  'type': 'text',
                                  'sql_type': 'nvarchar',
                                  'nullable': True,
                                  'sum_allowed': False},
                        'phone': {'column': 'Telephone1',
                                  'type': 'text',
                                  'sql_type': 'nvarchar',
                                  'nullable': True,
                                  'sum_allowed': False},
                        'mobile': {'column': 'MobilePhone',
                                   'type': 'text',
                                   'sql_type': 'nvarchar',
                                   'nullable': True,
                                   'sum_allowed': False},
                        'created_at': {'column': 'CreatedOn',
                                       'type': 'date',
                                       'sql_type': 'datetime',
                                       'nullable': True,
                                       'sum_allowed': False,
                                       'semantics': 'stored CRM timestamp; never infer stage entry or '
                                                    'field-change event'},
                        'updated_at': {'column': 'ModifiedOn',
                                       'type': 'date',
                                       'sql_type': 'datetime',
                                       'nullable': True,
                                       'sum_allowed': False,
                                       'semantics': 'stored CRM timestamp; never infer stage entry or '
                                                    'field-change event'},
                        'parent_id': {'column': 'ParentCustomerId',
                                      'type': 'identity',
                                      'sql_type': 'uniqueidentifier',
                                      'nullable': True,
                                      'sum_allowed': False},
                        'parent_type': {'column': 'ParentCustomerIdType',
                                        'type': 'number',
                                        'sql_type': 'int',
                                        'nullable': True,
                                        'sum_allowed': False}},
             'active_predicate': '1=1 AND {alias}.[statuscode]=1',
             'predicate_columns': ['statuscode'],
             'provenance': 'crm_inventory_20260930_r2',
             'semantic_notes': ['Contact is not automatically an author; author participation role and '
                                'stored is_author flag are distinct definitions.']},
 'participation': {'table': 'new_eserkatilimBase',
                   'schema': 'dbo',
                   'primary_key': 'link_id',
                   'grain': 'one physical source record',
                   'fields': {'link_id': {'column': 'new_eserkatilimId',
                                          'type': 'identity',
                                          'sql_type': 'uniqueidentifier',
                                          'nullable': False,
                                          'sum_allowed': False},
                              'book_id': {'column': 'new_Kitap',
                                          'type': 'identity',
                                          'sql_type': 'uniqueidentifier',
                                          'nullable': True,
                                          'sum_allowed': False},
                              'person_id': {'column': 'new_Katilimsaglayan',
                                            'type': 'identity',
                                            'sql_type': 'uniqueidentifier',
                                            'nullable': True,
                                            'sum_allowed': False},
                              'role_id': {'column': 'new_katilimciTipi',
                                          'type': 'identity',
                                          'sql_type': 'uniqueidentifier',
                                          'nullable': True,
                                          'sum_allowed': False},
                              'statecode': {'column': 'statecode',
                                            'type': 'number',
                                            'sql_type': 'int',
                                            'nullable': False,
                                            'sum_allowed': False},
                              'statuscode': {'column': 'statuscode',
                                             'type': 'number',
                                             'sql_type': 'int',
                                             'nullable': True,
                                             'sum_allowed': False}},
                   'active_predicate': '{alias}.[statecode]=0',
                   'predicate_columns': ['statecode'],
                   'provenance': 'crm_inventory_20260930_r2',
                   'semantic_notes': []},
 'participation_role': {'table': 'new_katilimcitipiBase',
                        'schema': 'dbo',
                        'primary_key': 'role_id',
                        'grain': 'one physical source record',
                        'fields': {'role_id': {'column': 'new_katilimcitipiId',
                                               'type': 'identity',
                                               'sql_type': 'uniqueidentifier',
                                               'nullable': False,
                                               'sum_allowed': False},
                                   'name': {'column': 'new_name',
                                            'type': 'text',
                                            'sql_type': 'nvarchar',
                                            'nullable': True,
                                            'sum_allowed': False},
                                   'statecode': {'column': 'statecode',
                                                 'type': 'number',
                                                 'sql_type': 'int',
                                                 'nullable': False,
                                                 'sum_allowed': False},
                                   'statuscode': {'column': 'statuscode',
                                                  'type': 'number',
                                                  'sql_type': 'int',
                                                  'nullable': True,
                                                  'sum_allowed': False}},
                        'active_predicate': '{alias}.[statecode]=0',
                        'predicate_columns': ['statecode'],
                        'provenance': 'crm_inventory_20260930_r2',
                        'semantic_notes': []},
 'contract': {'table': 'new_sozlesmeBase',
              'schema': 'dbo',
              'primary_key': 'contract_id',
              'grain': 'one physical source record',
              'fields': {'contract_id': {'column': 'new_sozlesmeId',
                                         'type': 'identity',
                                         'sql_type': 'uniqueidentifier',
                                         'nullable': False,
                                         'sum_allowed': False},
                         'contract_number': {'column': 'new_name',
                                             'type': 'text',
                                             'sql_type': 'nvarchar',
                                             'nullable': True,
                                             'sum_allowed': False},
                         'start_date': {'column': 'new_SozlesmeBaslangicTarihi',
                                        'type': 'date',
                                        'sql_type': 'datetime',
                                        'nullable': True,
                                        'sum_allowed': False,
                                        'semantics': 'stored CRM timestamp; never infer stage entry or '
                                                     'field-change event'},
                         'end_date': {'column': 'new_SozlesmeBitisTarihi',
                                      'type': 'date',
                                      'sql_type': 'datetime',
                                      'nullable': True,
                                      'sum_allowed': False,
                                      'semantics': 'stored CRM timestamp; never infer stage entry or '
                                                   'field-change event'},
                         'revised_end_date': {'column': 'new_revizebitistarihi',
                                              'type': 'date',
                                              'sql_type': 'datetime',
                                              'nullable': True,
                                              'sum_allowed': False,
                                              'semantics': 'stored CRM timestamp; never infer stage entry or '
                                                           'field-change event'},
                         'renewal_start_date': {'column': 'new_yenilemebaslangictarihi',
                                                'type': 'date',
                                                'sql_type': 'datetime',
                                                'nullable': True,
                                                'sum_allowed': False,
                                                'semantics': 'stored CRM timestamp; never infer stage entry '
                                                             'or field-change event'},
                         'renewal_end_date': {'column': 'new_yenilemebitistarihi',
                                              'type': 'date',
                                              'sql_type': 'datetime',
                                              'nullable': True,
                                              'sum_allowed': False,
                                              'semantics': 'stored CRM timestamp; never infer stage entry or '
                                                           'field-change event'},
                         'termination_date': {'column': 'new_fesihtarihi',
                                              'type': 'date',
                                              'sql_type': 'datetime',
                                              'nullable': True,
                                              'sum_allowed': False,
                                              'semantics': 'stored CRM timestamp; never infer stage entry or '
                                                           'field-change event'},
                         'indefinite_flag': {'column': 'new_suresizsozlesme',
                                             'type': 'bool',
                                             'sql_type': 'bit',
                                             'nullable': True,
                                             'sum_allowed': False},
                         'parent_contract_text': {'column': 'new_anasozlesmeid',
                                                  'type': 'text',
                                                  'sql_type': 'nvarchar',
                                                  'nullable': True,
                                                  'sum_allowed': False},
                         'protocol_date': {'column': 'new_ekprotokoltarihi',
                                           'type': 'date',
                                           'sql_type': 'datetime',
                                           'nullable': True,
                                           'sum_allowed': False,
                                           'semantics': 'stored CRM timestamp; never infer stage entry or '
                                                        'field-change event'},
                         'protocol_end_date': {'column': 'new_ekprotokolbitist',
                                               'type': 'date',
                                               'sql_type': 'datetime',
                                               'nullable': True,
                                               'sum_allowed': False,
                                               'semantics': 'stored CRM timestamp; never infer stage entry '
                                                            'or field-change event'},
                         'is_addendum': {'column': 'new_EkProtokolyeni',
                                         'type': 'bool',
                                         'sql_type': 'bit',
                                         'nullable': True,
                                         'sum_allowed': False},
                         'addendum_time_limited': {'column': 'new_ekprotokolsurelimi',
                                                   'type': 'bool',
                                                   'sql_type': 'bit',
                                                   'nullable': True,
                                                   'sum_allowed': False},
                         'statecode': {'column': 'statecode',
                                       'type': 'number',
                                       'sql_type': 'int',
                                       'nullable': False,
                                       'sum_allowed': False},
                         'statuscode': {'column': 'statuscode',
                                        'type': 'number',
                                        'sql_type': 'int',
                                        'nullable': True,
                                        'sum_allowed': False}},
              'active_predicate': '{alias}.[statecode]=0',
              'predicate_columns': ['statecode'],
              'provenance': 'crm_inventory_20260930_r2',
              'semantic_notes': ['Parent text is not a lookup, legal precedence or chronology. All '
                                 'revision/renewal/protocol dates are separate observations.']},
 'contract_book': {'table': 'new_new_sozlesme_new_kitapBase',
                   'schema': 'dbo',
                   'primary_key': 'link_id',
                   'grain': 'one physical source record',
                   'fields': {'link_id': {'column': 'new_new_sozlesme_new_kitapId',
                                          'type': 'identity',
                                          'sql_type': 'uniqueidentifier',
                                          'nullable': False,
                                          'sum_allowed': False},
                              'contract_id': {'column': 'new_sozlesmeid',
                                              'type': 'identity',
                                              'sql_type': 'uniqueidentifier',
                                              'nullable': False,
                                              'sum_allowed': False},
                              'book_id': {'column': 'new_kitapid',
                                          'type': 'identity',
                                          'sql_type': 'uniqueidentifier',
                                          'nullable': False,
                                          'sum_allowed': False}},
                   'active_predicate': '1=1',
                   'predicate_columns': [],
                   'provenance': 'crm_inventory_20260930_r2',
                   'semantic_notes': []},
 'contract_party': {'table': 'new_sozlesmetarafiBase',
                    'schema': 'dbo',
                    'primary_key': 'party_id',
                    'grain': 'one physical source record',
                    'fields': {'party_id': {'column': 'new_sozlesmetarafiId',
                                            'type': 'identity',
                                            'sql_type': 'uniqueidentifier',
                                            'nullable': False,
                                            'sum_allowed': False},
                               'contract_id': {'column': 'new_sozlesmeid',
                                               'type': 'identity',
                                               'sql_type': 'uniqueidentifier',
                                               'nullable': True,
                                               'sum_allowed': False},
                               'person_id': {'column': 'new_kisi',
                                             'type': 'identity',
                                             'sql_type': 'uniqueidentifier',
                                             'nullable': True,
                                             'sum_allowed': False},
                               'account_id': {'column': 'new_Firma',
                                              'type': 'identity',
                                              'sql_type': 'uniqueidentifier',
                                              'nullable': True,
                                              'sum_allowed': False},
                               'party_type_id': {'column': 'new_TarafTipi',
                                                 'type': 'identity',
                                                 'sql_type': 'uniqueidentifier',
                                                 'nullable': True,
                                                 'sum_allowed': False},
                               'statecode': {'column': 'statecode',
                                             'type': 'number',
                                             'sql_type': 'int',
                                             'nullable': False,
                                             'sum_allowed': False},
                               'statuscode': {'column': 'statuscode',
                                              'type': 'number',
                                              'sql_type': 'int',
                                              'nullable': True,
                                              'sum_allowed': False}},
                    'active_predicate': '{alias}.[statecode]=0',
                    'predicate_columns': ['statecode'],
                    'provenance': 'crm_inventory_20260930_r2',
                    'semantic_notes': []},
 'contract_party_type': {'table': 'new_sozlesmetaraftipiBase',
                         'schema': 'dbo',
                         'primary_key': 'party_type_id',
                         'grain': 'one physical source record',
                         'fields': {'party_type_id': {'column': 'new_sozlesmetaraftipiId',
                                                      'type': 'identity',
                                                      'sql_type': 'uniqueidentifier',
                                                      'nullable': False,
                                                      'sum_allowed': False},
                                    'name': {'column': 'new_name',
                                             'type': 'text',
                                             'sql_type': 'nvarchar',
                                             'nullable': True,
                                             'sum_allowed': False},
                                    'statecode': {'column': 'statecode',
                                                  'type': 'number',
                                                  'sql_type': 'int',
                                                  'nullable': False,
                                                  'sum_allowed': False},
                                    'statuscode': {'column': 'statuscode',
                                                   'type': 'number',
                                                   'sql_type': 'int',
                                                   'nullable': True,
                                                   'sum_allowed': False}},
                         'active_predicate': '{alias}.[statecode]=0',
                         'predicate_columns': ['statecode'],
                         'provenance': 'crm_inventory_20260930_r2',
                         'semantic_notes': []},
 'account': {'table': 'AccountBase',
             'schema': 'dbo',
             'primary_key': 'account_id',
             'grain': 'one physical source record',
             'fields': {'account_id': {'column': 'AccountId',
                                       'type': 'identity',
                                       'sql_type': 'uniqueidentifier',
                                       'nullable': False,
                                       'sum_allowed': False},
                        'name': {'column': 'Name',
                                 'type': 'text',
                                 'sql_type': 'nvarchar',
                                 'nullable': True,
                                 'sum_allowed': False},
                        'tax_number': {'column': 'new_VergiNo',
                                       'type': 'text',
                                       'sql_type': 'nvarchar',
                                       'nullable': True,
                                       'sum_allowed': False}},
             'active_predicate': '1=1',
             'predicate_columns': [],
             'provenance': 'crm_inventory_20260930_r2',
             'semantic_notes': ['Active organization, not necessarily active customer-status account.']},
 'work': {'table': 'new_isplaniBase',
          'schema': 'dbo',
          'primary_key': 'work_id',
          'grain': 'one physical source record',
          'fields': {'work_id': {'column': 'new_isplaniId',
                                 'type': 'identity',
                                 'sql_type': 'uniqueidentifier',
                                 'nullable': False,
                                 'sum_allowed': False},
                     'work_name': {'column': 'new_planadi',
                                   'type': 'text',
                                   'sql_type': 'nvarchar',
                                   'nullable': True,
                                   'sum_allowed': False},
                     'project_id': {'column': 'new_projeid',
                                    'type': 'identity',
                                    'sql_type': 'uniqueidentifier',
                                    'nullable': True,
                                    'sum_allowed': False},
                     'owner_id': {'column': 'OwnerId',
                                  'type': 'identity',
                                  'sql_type': 'uniqueidentifier',
                                  'nullable': False,
                                  'sum_allowed': False},
                     'stage_id': {'column': 'new_projeasamasiid',
                                  'type': 'identity',
                                  'sql_type': 'uniqueidentifier',
                                  'nullable': True,
                                  'sum_allowed': False},
                     'due_date': {'column': 'new_tahminibitistarihi',
                                  'type': 'date',
                                  'sql_type': 'datetime',
                                  'nullable': True,
                                  'sum_allowed': False,
                                  'semantics': 'stored CRM timestamp; never infer stage entry or '
                                               'field-change event'},
                     'actual_end': {'column': 'new_gercekbitistarihi',
                                    'type': 'date',
                                    'sql_type': 'datetime',
                                    'nullable': True,
                                    'sum_allowed': False,
                                    'semantics': 'stored CRM timestamp; never infer stage entry or '
                                                 'field-change event'},
                     'work_state': {'column': 'new_isEmriDurumu',
                                    'type': 'number',
                                    'sql_type': 'int',
                                    'nullable': True,
                                    'sum_allowed': False},
                     'cancelled': {'column': 'new_isplaniiptal',
                                   'type': 'bool',
                                   'sql_type': 'bit',
                                   'nullable': True,
                                   'sum_allowed': False},
                     'created_at': {'column': 'CreatedOn',
                                    'type': 'date',
                                    'sql_type': 'datetime',
                                    'nullable': True,
                                    'sum_allowed': False,
                                    'semantics': 'stored CRM timestamp; never infer stage entry or '
                                                 'field-change event'},
                     'updated_at': {'column': 'ModifiedOn',
                                    'type': 'date',
                                    'sql_type': 'datetime',
                                    'nullable': True,
                                    'sum_allowed': False,
                                    'semantics': 'stored CRM timestamp; never infer stage entry or '
                                                 'field-change event'},
                     'statecode': {'column': 'statecode',
                                   'type': 'number',
                                   'sql_type': 'int',
                                   'nullable': False,
                                   'sum_allowed': False},
                     'statuscode': {'column': 'statuscode',
                                    'type': 'number',
                                    'sql_type': 'int',
                                    'nullable': True,
                                    'sum_allowed': False}},
          'active_predicate': '{alias}.[statecode]=0',
          'predicate_columns': ['statecode'],
          'provenance': 'crm_inventory_20260930_r2',
          'semantic_notes': ['Active includes completed/cancelled work. Open-work scope needs explicit '
                             'filters.',
                             'ModifiedOn is not stage entry.']},
 'project': {'table': 'new_projeBase',
             'schema': 'dbo',
             'primary_key': 'project_id',
             'grain': 'one physical source record',
             'fields': {'project_id': {'column': 'new_projeId',
                                       'type': 'identity',
                                       'sql_type': 'uniqueidentifier',
                                       'nullable': False,
                                       'sum_allowed': False},
                        'project_name': {'column': 'new_name',
                                         'type': 'text',
                                         'sql_type': 'nvarchar',
                                         'nullable': True,
                                         'sum_allowed': False},
                        'stock_card_id': {'column': 'new_stakkarti',
                                          'type': 'identity',
                                          'sql_type': 'uniqueidentifier',
                                          'nullable': True,
                                          'sum_allowed': False,
                                          'semantics': "Project's book (Stok Kartı); with book.project_card_id/book_project_id "
                                                       'this is the book-project link'},
                        'statecode': {'column': 'statecode',
                                      'type': 'number',
                                      'sql_type': 'int',
                                      'nullable': False,
                                      'sum_allowed': False},
                        'statuscode': {'column': 'statuscode',
                                       'type': 'number',
                                       'sql_type': 'int',
                                       'nullable': True,
                                       'sum_allowed': False}},
             'active_predicate': '{alias}.[statecode]=0',
             'predicate_columns': ['statecode'],
             'provenance': 'crm_inventory_20260930_r2',
             'semantic_notes': []},
 'project_stage': {'table': 'new_projeasamalariBase',
                   'schema': 'dbo',
                   'primary_key': 'stage_id',
                   'grain': 'one physical source record',
                   'fields': {'stage_id': {'column': 'new_projeasamalariId',
                                           'type': 'identity',
                                           'sql_type': 'uniqueidentifier',
                                           'nullable': False,
                                           'sum_allowed': False},
                              'stage_name': {'column': 'new_name',
                                             'type': 'text',
                                             'sql_type': 'nvarchar',
                                             'nullable': True,
                                             'sum_allowed': False},
                              'statecode': {'column': 'statecode',
                                            'type': 'number',
                                            'sql_type': 'int',
                                            'nullable': False,
                                            'sum_allowed': False},
                              'statuscode': {'column': 'statuscode',
                                             'type': 'number',
                                             'sql_type': 'int',
                                             'nullable': True,
                                             'sum_allowed': False}},
                   'active_predicate': '{alias}.[statecode]=0',
                   'predicate_columns': ['statecode'],
                   'provenance': 'crm_inventory_20260930_r2',
                   'semantic_notes': []}}

RELATION_REGISTRY = {'work_project_id_to_project': {'left_entity': 'work',
                                'right_entity': 'project',
                                'left_field': 'project_id',
                                'right_field': 'project_id',
                                'cardinality': 'many_to_one',
                                'nullable': True,
                                'target_unique': True,
                                'provenance': 'new_new_proje_new_isplani_projeid',
                                'semantic_note': 'Physical FK to unique PK; active endpoint may be '
                                                 'unresolved. Reverse traversal can multiply grain.'},
 'book_book_project_id_to_project': {'left_entity': 'book',
                                     'right_entity': 'project',
                                     'left_field': 'book_project_id',
                                     'right_field': 'project_id',
                                     'cardinality': 'many_to_one',
                                     'nullable': True,
                                     'target_unique': True,
                                     'provenance': 'new_new_proje_new_kitap_KitapProjesi',
                                     'semantic_note': 'Physical FK to unique PK; active endpoint may be '
                                                      'unresolved. Reverse traversal can multiply grain.'},
 'book_project_card_id_to_project': {'left_entity': 'book',
                                     'right_entity': 'project',
                                     'left_field': 'project_card_id',
                                     'right_field': 'project_id',
                                     'cardinality': 'many_to_one',
                                     'nullable': True,
                                     'target_unique': True,
                                     'provenance': 'new_new_proje_new_kitap_projekarti',
                                     'semantic_note': 'Physical FK to unique PK; active endpoint may be '
                                                      'unresolved. Reverse traversal can multiply grain.'},
 'project_stock_card_id_to_book': {'left_entity': 'project',
                                   'right_entity': 'book',
                                   'left_field': 'stock_card_id',
                                   'right_field': 'book_id',
                                   'cardinality': 'many_to_one',
                                   'nullable': True,
                                   'target_unique': True,
                                   'provenance': 'new_new_kitap_new_proje_stakkarti',
                                   'semantic_note': 'Physical FK to unique PK; active endpoint may be '
                                                    'unresolved. Reverse traversal can multiply grain.'},
 'contract_book_contract_id_to_contract': {'left_entity': 'contract_book',
                                           'right_entity': 'contract',
                                           'left_field': 'contract_id',
                                           'right_field': 'contract_id',
                                           'cardinality': 'many_to_one',
                                           'nullable': False,
                                           'target_unique': True,
                                           'provenance': 'new_new_sozlesme_new_kitapOne',
                                           'semantic_note': 'Physical FK to unique PK; active endpoint may '
                                                            'be unresolved. Reverse traversal can multiply '
                                                            'grain.'},
 'contract_party_contract_id_to_contract': {'left_entity': 'contract_party',
                                            'right_entity': 'contract',
                                            'left_field': 'contract_id',
                                            'right_field': 'contract_id',
                                            'cardinality': 'many_to_one',
                                            'nullable': True,
                                            'target_unique': True,
                                            'provenance': 'new_new_sozlesme_new_sozlesmetarafi_sozlesmeid',
                                            'semantic_note': 'Physical FK to unique PK; active endpoint may '
                                                             'be unresolved. Reverse traversal can multiply '
                                                             'grain.'},
 'participation_person_id_to_contact': {'left_entity': 'participation',
                                        'right_entity': 'contact',
                                        'left_field': 'person_id',
                                        'right_field': 'person_id',
                                        'cardinality': 'many_to_one',
                                        'nullable': True,
                                        'target_unique': True,
                                        'provenance': 'new_contact_new_eserkatilim_Katilimsaglayan',
                                        'semantic_note': 'Physical FK to unique PK; active endpoint may be '
                                                         'unresolved. Reverse traversal can multiply grain.'},
 'contract_party_person_id_to_contact': {'left_entity': 'contract_party',
                                         'right_entity': 'contact',
                                         'left_field': 'person_id',
                                         'right_field': 'person_id',
                                         'cardinality': 'many_to_one',
                                         'nullable': True,
                                         'target_unique': True,
                                         'provenance': 'new_contact_new_sozlesmetarafi_kisi',
                                         'semantic_note': 'Physical FK to unique PK; active endpoint may be '
                                                          'unresolved. Reverse traversal can multiply '
                                                          'grain.'},
 'participation_role_id_to_participation_role': {'left_entity': 'participation',
                                                 'right_entity': 'participation_role',
                                                 'left_field': 'role_id',
                                                 'right_field': 'role_id',
                                                 'cardinality': 'many_to_one',
                                                 'nullable': True,
                                                 'target_unique': True,
                                                 'provenance': 'new_new_katilimcitipi_new_eserkatilim_katilimciTipi',
                                                 'semantic_note': 'Physical FK to unique PK; active endpoint '
                                                                  'may be unresolved. Reverse traversal can '
                                                                  'multiply grain.'},
 'work_stage_id_to_project_stage': {'left_entity': 'work',
                                    'right_entity': 'project_stage',
                                    'left_field': 'stage_id',
                                    'right_field': 'stage_id',
                                    'cardinality': 'many_to_one',
                                    'nullable': True,
                                    'target_unique': True,
                                    'provenance': 'new_new_projeasamalari_new_isplani_projeasamasiid',
                                    'semantic_note': 'Physical FK to unique PK; active endpoint may be '
                                                     'unresolved. Reverse traversal can multiply grain.'},
 'contract_party_party_type_id_to_contract_party_type': {'left_entity': 'contract_party',
                                                         'right_entity': 'contract_party_type',
                                                         'left_field': 'party_type_id',
                                                         'right_field': 'party_type_id',
                                                         'cardinality': 'many_to_one',
                                                         'nullable': True,
                                                         'target_unique': True,
                                                         'provenance': 'new_new_sozlesmetaraftipi_new_sozlesmetarafi_TarafTipi',
                                                         'semantic_note': 'Physical FK to unique PK; active '
                                                                          'endpoint may be unresolved. '
                                                                          'Reverse traversal can multiply '
                                                                          'grain.'},
 'participation_book_id_to_book': {'left_entity': 'participation',
                                   'right_entity': 'book',
                                   'left_field': 'book_id',
                                   'right_field': 'book_id',
                                   'cardinality': 'many_to_one',
                                   'nullable': True,
                                   'target_unique': True,
                                   'provenance': 'new_new_kitap_new_eserkatilim_Kitap',
                                   'semantic_note': 'Physical FK to unique PK; active endpoint may be '
                                                    'unresolved. Reverse traversal can multiply grain.'},
 'contract_book_book_id_to_book': {'left_entity': 'contract_book',
                                   'right_entity': 'book',
                                   'left_field': 'book_id',
                                   'right_field': 'book_id',
                                   'cardinality': 'many_to_one',
                                   'nullable': False,
                                   'target_unique': True,
                                   'provenance': 'new_new_sozlesme_new_kitapTwo',
                                   'semantic_note': 'Physical FK to unique PK; active endpoint may be '
                                                    'unresolved. Reverse traversal can multiply grain.'},
 'book_subbrand_id_to_publisher': {'left_entity': 'book',
                                   'right_entity': 'publisher',
                                   'left_field': 'subbrand_id',
                                   'right_field': 'publisher_id',
                                   'cardinality': 'many_to_one',
                                   'nullable': True,
                                   'target_unique': True,
                                   'provenance': 'new_new_marka_new_kitap_yayinciid',
                                   'semantic_note': 'Physical FK to unique PK; active endpoint may be '
                                                    'unresolved. Reverse traversal can multiply grain.'},
 'book_publisher_id_to_publisher': {'left_entity': 'book',
                                    'right_entity': 'publisher',
                                    'left_field': 'publisher_id',
                                    'right_field': 'publisher_id',
                                    'cardinality': 'many_to_one',
                                    'nullable': True,
                                    'target_unique': True,
                                    'provenance': 'new_new_marka_new_kitap_yayineviid',
                                    'semantic_note': 'Physical FK to unique PK; active endpoint may be '
                                                     'unresolved. Reverse traversal can multiply grain.'},
 'book_alternate_subbrand_id_to_alternate_subbrand': {'left_entity': 'book',
                                                      'right_entity': 'alternate_subbrand',
                                                      'left_field': 'alternate_subbrand_id',
                                                      'right_field': 'subbrand_id',
                                                      'cardinality': 'many_to_one',
                                                      'nullable': True,
                                                      'target_unique': True,
                                                      'provenance': 'new_new_yaynevialtmarka_new_kitap_YayneviAltMarka',
                                                      'semantic_note': 'Physical FK to unique PK; active '
                                                                       'endpoint may be unresolved. Reverse '
                                                                       'traversal can multiply grain.'},
 'book_previous_publisher_id_to_account': {'left_entity': 'book',
                                           'right_entity': 'account',
                                           'left_field': 'previous_publisher_id',
                                           'right_field': 'account_id',
                                           'cardinality': 'many_to_one',
                                           'nullable': True,
                                           'target_unique': True,
                                           'provenance': 'new_account_new_kitap_oncekiyayineviid',
                                           'semantic_note': 'Physical FK to unique PK; active endpoint may '
                                                            'be unresolved. Reverse traversal can multiply '
                                                            'grain.'},
 'contract_party_account_id_to_account': {'left_entity': 'contract_party',
                                          'right_entity': 'account',
                                          'left_field': 'account_id',
                                          'right_field': 'account_id',
                                          'cardinality': 'many_to_one',
                                          'nullable': True,
                                          'target_unique': True,
                                          'provenance': 'new_account_new_sozlesmetarafi_Firma',
                                          'semantic_note': 'Physical FK to unique PK; active endpoint may be '
                                                           'unresolved. Reverse traversal can multiply '
                                                           'grain.'}}

EXCLUDED_RELATIONSHIPS = {'contract_parent_text': 'Text UUID does not prove lookup/chronology/legal precedence.',
 'owner_user': 'OwnerId polymorphic target type not constrained here.',
 'stage_entry_history': 'ModifiedOn is not stage entry; Audit old/new and complete event coverage '
                        'unverified.',
 'publisher_hierarchy': 'Publisher/subbrand lookup coexistence is not hierarchy.',
 'author_name_identity': 'Name and author text are not person identity.',
 'work_identity': 'Title/ISBN similarity is not work/edition identity.',
 'contract_scope_precedence': 'Country-region AND/OR and legal priority unverified.',
 'reverse_fanout': 'Reverse traversal and inferred many-to-many joins forbidden in initial compiler.',
 'unknown_edges': 'No edge without physical FK and unique target PK evidence.',
 'project_book_nn': 'new_new_proje_new_kitap N:N is not the book project (2026-10-01: 14 of 722 active pairs '
                    'match the card lookups); use book.project_card_id/book_project_id or project.stock_card_id.'}

