"""Page-local sources before interpretation. Captions are never source text.

Source records are immutable; optical agreement is not editorial acceptance.
Unresolved regions remain visible and block dependent claims, not other pages.
"""
import base64
import json
import os
import re
import unicodedata

import httpx
from psycopg.types.json import Jsonb
from editor.book_store import ROOT, sha, identifier, get_records, source_for, fence
from editor.config import connection, code_manifest
from editor.source_alignment import reader_text, reading_order, valid_box

VERSION = 'source-spans-v16'


def same_model(metrics):
    # Legacy records were generated by the original local llama.cpp runner.
    # Source/OCR reuse is independent; model output must belong to this runner.
    return (metrics.get('model_name','editor-qwen38') == os.environ.get('EDITOR_MODEL_NAME','editor-qwen38')
            and metrics.get('model_backend','llama.cpp') == os.environ.get('EDITOR_MODEL_BACKEND','llama.cpp'))


def norm(value):
    value = re.sub(r'-\s*\n\s*', '', value)
    value = unicodedata.normalize('NFKC', value).replace('İ','i').replace('I','ı').lower()
    return ''.join(c for c in value if c.isalnum())


def negation(value):
    # A rejection aid, never sufficient to accept a sentence. Exact quote matching
    # below also catches forms this deliberately incomplete Turkish check misses.
    return re.findall(r'\b\w*(?:mıyor|miyor|muyor|müyor|madı|medi)\w*\b|\b(?:değil|yok|hayır)\b', value.lower())


def narrative_gate(page_role, source_gate):
    # A prompt or an inherited model candidate cannot exempt a claim from the
    # page-role rule. Metadata statements are not narrative facts either.
    if page_role in ('ACTIVITY', 'FRONT_MATTER', 'APPENDIX', 'UNKNOWN'):
        return 'NON_NARRATIVE_CLAIM_BLOCKED'
    if page_role not in ('NARRATIVE', 'MIXED'):
        return 'INVALID_PAGE_ROLE'
    return source_gate


def quote_tokens(value):
    value = re.sub(r'-\s*\n\s*', '', value)
    value = unicodedata.normalize('NFKC',value).replace('İ','i').replace('I','ı').lower()
    return re.findall(r'[^\W_]+',value)


def optical_verdict(line, secondary, pdf_text, pdf_usable, reread=None):
    # Preserve word boundaries, just as the downstream quote gate does. Joining
    # all letters hid split/merged words and could certify a different reading.
    primary_tokens = quote_tokens(line['text'])
    secondary_tokens = quote_tokens(secondary)
    primary = bool(primary_tokens) and primary_tokens == quote_tokens(line.get('region_text') or '')
    second = bool(secondary_tokens) and secondary_tokens == primary_tokens
    native = pdf_usable and bool(quote_tokens(pdf_text)) and quote_tokens(pdf_text) == primary_tokens
    conflict = (bool(secondary_tokens) and not second) or (pdf_usable and not native)
    score = min(line['score'], line.get('region_score') or 0)
    issues = []
    if not primary: issues.append('REGIONAL_READING_DISAGREES')
    if not second: issues.append('SECOND_READER_DISAGREES_OR_MISSING')
    if not native: issues.append('PDF_TEXT_DISAGREES_OR_UNUSABLE')
    if score < .9: issues.append('LOW_RECOGNITION_SCORE')
    # Stored "stable"/"matching" flags are diagnostic, not acceptance authority.
    # Recompute from the two immutable raw readings; a new contradiction blocks.
    reread_state = 'NOT_AVAILABLE'
    if reread is not None:
        readings = reread['readings']
        if len(readings) != 2 or [r['psm'] for r in readings] != [7,13]:
            raise RuntimeError('REREAD_SCHEMA_MISMATCH')
        tokens = [quote_tokens(r['text']) for r in readings]
        stable = bool(tokens[0]) and tokens[0] == tokens[1]
        reread_state = 'AGREES' if stable and tokens[0] == quote_tokens(line['text']) else 'DISAGREES' if stable else 'UNSTABLE'
        if reread_state == 'DISAGREES':
            conflict = True
            issues.append('REREAD_CONFLICT')
        elif reread_state == 'UNSTABLE':
            issues.append('REREAD_UNSTABLE')
    return {'status': 'TEXT_AGREED' if primary and (second or native) and not conflict and score >= .9 else 'NEEDS_REVIEW',
            'issues': issues, 'pdf_matches': native, 'reread_state': reread_state}


def reread_measurements(root, parent, evidence):
    if not parent:
        return {}, None
    path = root/'region-reread-v1'/str(parent)/f"page-{evidence['data']['pdf_page']:04}.json"
    if not path.exists():
        # A parent may itself reuse measurements. Follow the stored original
        # artifact identity, never silently lose reader conflicts on generation 3+.
        inherited={};provenance=None;reports={}
        for row in get_records(parent,'source_spans'):
            d=row['data']
            if d['pdf_page']!=evidence['data']['pdf_page'] or not d.get('reread_measurement'):
                continue
            p=d['reread_provenance'];origin=p['generation_id']
            if p.get('method')=='region-reread-queue-v1':
                from editor.reread_queue import load_verified
                if origin not in reports:
                    reports[origin]=load_verified(p,evidence)
                measurement=d['reread_measurement']
                if reports[origin].get(measurement['source_span_id'])!=measurement or measurement['bbox']!=d['bbox']:
                    raise RuntimeError('INHERITED_REREAD_MEASUREMENT_MISMATCH')
                if provenance is not None and provenance!=p:raise RuntimeError('MIXED_REREAD_PROVENANCE')
                provenance=p;inherited[str(row['id'])]=measurement
                continue
            if origin not in reports:
                original=root/'region-reread-v1'/origin/f"page-{d['pdf_page']:04}.json"
                raw=original.read_bytes();report=json.loads(raw)
                e=evidence['data']
                if (sha(raw)!=p['artifact_sha256'] or report['generation_id']!=origin
                        or report['source_sha256']!=e['source_sha256'] or report['pdf_page']!=e['pdf_page']
                        or report['render_sha256']!=e['ocr_render_sha256']):
                    raise RuntimeError('INHERITED_REREAD_SOURCE_MISMATCH')
                reports[origin]={r['source_span_id']:r for r in report['regions']}
                if len(reports[origin])!=len(report['regions']):raise RuntimeError('DUPLICATE_REREAD_SOURCE')
            measurement=d['reread_measurement']
            if reports[origin].get(measurement['source_span_id'])!=measurement or measurement['bbox']!=d['bbox']:
                raise RuntimeError('INHERITED_REREAD_MEASUREMENT_MISMATCH')
            if provenance is not None and provenance!=p:raise RuntimeError('MIXED_REREAD_PROVENANCE')
            provenance=p;inherited[str(row['id'])]=measurement
        return inherited, provenance
    raw = path.read_bytes(); report = json.loads(raw); d = evidence['data']
    if (report['generation_id'] != str(parent) or report['source_sha256'] != d['source_sha256']
            or report['render_sha256'] != d['ocr_render_sha256'] or report['pdf_page'] != d['pdf_page']):
        raise RuntimeError('REREAD_SOURCE_SCOPE_MISMATCH')
    rows = {r['source_span_id']:r for r in report['regions']}
    if len(rows) != len(report['regions']):
        raise RuntimeError('DUPLICATE_REREAD_SOURCE')
    return rows, {'artifact_sha256':sha(raw),'generation_id':str(parent),
                  'method':report['method'],'code_sha256':report['code_sha256'],
                  'engine':report['engine'],'models':report['models']}


def quote_check(quote, rows, all_rows=None):
    if not isinstance(quote,str) or not quote_tokens(quote) or not rows:
        return 'QUOTE_MISMATCH'
    ids=[str(r['id']) for r in rows]
    if len(set(ids))!=len(ids): return 'DUPLICATE_SPAN_REFERENCE'
    if all_rows is not None:
        positions={str(r['id']):i for i,r in enumerate(reading_order(all_rows))}
        order=[positions.get(r,-1) for r in ids]
        if -1 in order or order!=list(range(order[0],order[0]+len(order))):
            return 'NONCONTIGUOUS_SOURCE_SPANS'
    joined='\n'.join(r['data']['text'] for r in rows)
    needle=quote_tokens(quote); haystack=quote_tokens(joined)
    if any(haystack[i:i+len(needle)]==needle for i in range(len(haystack)-len(needle)+1)):
        return 'MATCH' if rows and all(r['data']['status']=='TEXT_AGREED' for r in rows) else 'SOURCE_NEEDS_REVIEW'
    if rows and bool(negation(quote)) != bool(negation(joined)):
        return 'POSSIBLE_NEGATION_FLIP'
    return 'QUOTE_MISMATCH'


def save(job, kind, key, data):
    from editor.analysis import commit
    return commit(job, kind, key, data)


def reused_reading(parent,evidence):
    """Reuse immutable machine measurements, never claims or review decisions."""
    if not parent: return None
    key=evidence['record_key']; page=evidence['data']['pdf_page']
    readings={r['record_key']:r for r in get_records(parent,'page_readings')}
    layouts={r['record_key']:r for r in get_records(parent,'layout_regions')}
    prior={r['record_key']:r for r in get_records(parent,'evidence')}
    if key not in readings or key not in layouts or key not in prior: return None
    previous=prior[key]['data']; current=evidence['data']
    if any(previous[k]!=current[k] for k in ('source_sha256','render_sha256','ocr_render_sha256','ocr_artifact_sha256')):
        raise RuntimeError('REUSED_SOURCE_HASH_MISMATCH')
    spans=[r for r in get_records(parent,'source_spans') if r['data']['pdf_page']==page]
    reading=readings[key]['data']
    if len(spans)!=reading['span_count']: raise RuntimeError('REUSED_SOURCE_INCOMPLETE')
    lines=[]
    for row in spans:
        d=row['data'];x,y,w,h=d['bbox']
        if d['render_sha256']!=current['ocr_render_sha256']:raise RuntimeError('REUSED_RENDER_MISMATCH')
        lines.append({'text':d['raw_text'],'score':d['score'],'region_text':d['region_text'],
            'region_score':d['region_score'],'polygon':[[x,y],[x+w,y],[x+w,y+h],[x,y+h]],
            'bbox':d['bbox'],
            'reused_source_span_id':str(row['id'])})
    return {'width':1,'height':1,'image_sha256':current['ocr_render_sha256'],'lines':lines,
        'engine':spans[0]['data']['engine'] if spans else 'paddleocr',
        'models':reading['model_manifest'],'seconds':reading['seconds'],
        'regional_truncated':reading['regional_truncated'],
        'balloon_candidates':layouts[key]['data'].get('balloon_candidates',[]),
        'balloons_truncated':layouts[key]['data'].get('balloons_truncated',False),
        'reused_from_generation':str(parent),'reused_reading_id':str(readings[key]['id'])}


def optical(job, evidence, document, root, parent=None, on_layout=None):
    gen=job['generation_id']; page=evidence['data']['pdf_page']; key=evidence['record_key']
    d=evidence['data']; image_path=root/'ocr-regions-v2'/f'page-{page:04}.png'
    raw=image_path.read_bytes()
    if sha(raw)!=d['ocr_render_sha256']: raise RuntimeError('OCR_RENDER_HASH_MISMATCH')
    result=reused_reading(parent,evidence)
    if result is None:
        with httpx.Client(timeout=600,trust_env=False) as client:
            response=client.post('http://ocr:8080/ocr',json={
                'image_base64':base64.b64encode(raw).decode(),'regional_pass':True})
            response.raise_for_status(); result=response.json()
    if result['image_sha256']!=sha(raw): raise RuntimeError('OCR_RESPONSE_SOURCE_MISMATCH')
    width,height=result['width'],result['height']; spans=[]
    pdf_path=root/'pdf-text-regions-v1'/f'page-{page:04}.json'
    if not pdf_path.exists():raise RuntimeError('NATIVE_PDF_REGIONS_REQUIRED')
    pdf=json.loads(pdf_path.read_text())
    if pdf['source_sha256']!=d['source_sha256'] or pdf['pdf_page']!=page:raise RuntimeError('PDF_SOURCE_SCOPE_MISMATCH')
    rereads, reread_provenance = reread_measurements(root,parent,evidence)
    from editor.optical_selection import select_regional_candidate, word_tokens
    drafts=[]
    for i,line in enumerate(result['lines']):
        xs=[p[0] for p in line['polygon']];ys=[p[1] for p in line['polygon']]
        bbox=line.get('bbox') or [min(xs)/width,min(ys)/height,(max(xs)-min(xs))/width,(max(ys)-min(ys))/height]
        line={**line,'bbox':bbox}
        secondary,neighbors,_=reader_text(bbox,d['blocks'])
        pdf_text,pdf_neighbors,pdf_usable=reader_text(bbox,pdf['lines'])
        reread=rereads.get(line.get('reused_source_span_id'))
        if reread is not None and reread['bbox']!=bbox:raise RuntimeError('REREAD_REGION_MISMATCH')
        verdict=optical_verdict(line,secondary,pdf_text,pdf_usable,reread)
        selection=select_regional_candidate(line,secondary,pdf_text,pdf_usable,reread)
        needs_review=verdict['status']!='TEXT_AGREED' and selection['selected_text'] is None
        drafts.append({'line':line,'secondary':secondary,'neighbors':neighbors,'pdf_text':pdf_text,
                       'pdf_neighbors':pdf_neighbors,'pdf_usable':pdf_usable,'reread':reread,
                       'needs_review':needs_review,'sid':str(identifier(gen,'source_spans',key+f'-{i:04}'))})
    regions=[]; size=document['pages'][str(page)]['size']
    for group in ('texts','pictures'):
        for item in document.get(group,[]):
            for p in item.get('prov',[]):
                if p['page_no']!=page: continue
                b=p['bbox']; top=(size['height']-b['t']) if b['coord_origin']=='BOTTOMLEFT' else b['t']
                x=max(0,b['l']/size['width']); y=max(0,top/size['height'])
                bbox=[x,y,min(1-x,abs(b['r']-b['l'])/size['width']),min(1-y,abs(b['t']-b['b'])/size['height'])]
                if min(bbox[2:])<=0: continue
                regions.append({'type':'PICTURE' if group=='pictures' else 'TEXT',
                    'label':item.get('label'),'bbox':bbox,'source_ref':item['self_ref']})
    layout_value={'pdf_page':page,'evidence_refs':[str(evidence['id'])],
        'regions':regions,'method':'existing_hash_verified_docling_layout',
        'native_pdf_regions':pdf['lines'],'native_pdf_artifact_sha256':sha(pdf_path.read_bytes()),
        'balloon_candidates':result.get('balloon_candidates',[]),
        'balloons_truncated':result.get('balloons_truncated',False),
        'source_artifact_sha256':sha((root/'docling.json').read_bytes()),
        'verification_status':'CANDIDATE','does_not_supply_text':True}
    save(job,'layout_regions',key,layout_value)
    if on_layout:
        on_layout({'data':layout_value}, [{'id':identifier(gen,'source_spans',key+f'-{i:04}')} for i in range(len(result['lines']))])
    generated_reread=False
    if any(draft['needs_review'] and draft['reread'] is None for draft in drafts):
        from editor.reread_queue import submit, await_result
        targets=[draft for draft in drafts if draft['needs_review'] or draft['reread'] is not None]
        def check_active():
            with connection() as db:fence(db,job)
        check_active()
        request=submit(gen,d['source_sha256'],page,d['ocr_render_sha256'],
                       [{'region_key':draft['sid'],'bbox':draft['line']['bbox']} for draft in targets],
                       attempt_token=job['fencing_token'])
        with connection() as db:
            fence(db,job)
            db.execute('UPDATE editor.jobs SET progress=%s WHERE id=%s',
                (Jsonb({'stage':'region_rereads','pdf_page':page,'region_count':len(targets),
                        'request_id':request['request_id']}),job['id']))
        measurements,reread_provenance=await_result(request,check_active=check_active)
        if set(measurements)!={draft['sid'] for draft in targets}:raise RuntimeError('REREAD_RESULT_INCOMPLETE')
        for draft in targets:
            draft['reread']=measurements[draft['sid']]
            if draft['reread']['bbox']!=draft['line']['bbox']:raise RuntimeError('REREAD_REGION_MISMATCH')
        generated_reread=True
    completed_spans={str(r['id']):r for r in get_records(gen,'source_spans')}
    for i,draft in enumerate(drafts):
        if draft['sid'] in completed_spans:
            stored=completed_spans[draft['sid']]
            if stored['data']['render_sha256']!=d['ocr_render_sha256'] or stored['data']['bbox']!=draft['line']['bbox']:
                raise RuntimeError('RESUMED_SPAN_SOURCE_MISMATCH')
            spans.append(stored)
            continue
        line=draft['line']
        bbox=line['bbox']
        # Match readers by position; never promote a similar word elsewhere on the page.
        secondary,neighbors=draft['secondary'],draft['neighbors']
        pdf_text,pdf_neighbors,pdf_usable=draft['pdf_text'],draft['pdf_neighbors'],draft['pdf_usable']
        reread = draft['reread']
        if reread is not None and reread['bbox'] != bbox:
            raise RuntimeError('REREAD_REGION_MISMATCH')
        verdict = optical_verdict(line,secondary,pdf_text,pdf_usable,reread)
        selection = select_regional_candidate(line,secondary,pdf_text,pdf_usable,reread)
        selected_text = line['text']
        selected_reader = 'FULL_PAGE_OCR'
        if verdict['status'] != 'TEXT_AGREED' and selection['selected_text'] is not None:
            selected_text = selection['selected_text']
            selected_reader = selection['selected_reader']
            verdict = {'status':'TEXT_AGREED', 'issues':['FULL_PAGE_READING_SUPERSEDED'],
                'pdf_matches':bool(pdf_usable and word_tokens(pdf_text)==word_tokens(selected_text)),
                'reread_state':selection['reread_state']}
        vl_measurement=None; vl_selection=None; vl_routing=None
        if verdict['status']!='TEXT_AGREED' and os.environ.get('EDITOR_OCR_VL_BASE_URL'):
            from editor.ocr_vl import read_region, select_supported, route_region
            vl_routing=route_region(line,secondary,pdf_text,pdf_usable,reread)
        if vl_routing and vl_routing['request_ocr']:
            with connection() as db: fence(db,job)
            vl_measurement=read_region(raw,d,bbox)
            with connection() as db: fence(db,job)
            vl_selection=select_supported(vl_measurement,line,secondary,pdf_text,pdf_usable,reread)
            if vl_selection['selected_text'] is not None:
                selected_text=vl_selection['selected_text']; selected_reader='PADDLEOCR_VL'
                verdict={**verdict,'status':'TEXT_AGREED','pdf_matches':vl_selection['pdf_matches'],
                         'issues':['OCR_VL_INDEPENDENTLY_SUPPORTED']}
        status,issues,pdf_agrees = verdict['status'],verdict['issues'],verdict['pdf_matches']
        sid=identifier(gen,'source_spans',key+f'-{i:04}')
        value={'pdf_page':page,'evidence_refs':[str(evidence['id'])], 'bbox':bbox,
            'coordinate_system':'normalized_top_left','text':selected_text,'raw_text':line['text'],
            'selected_reader':selected_reader,'regional_selection':selection,
            'ocr_vl_measurement':vl_measurement,'ocr_vl_selection':vl_selection,'ocr_vl_routing':vl_routing,
            'region_text':line.get('region_text'), 'secondary_text':secondary,
            'pdf_text':pdf_text,'pdf_usable':pdf_usable,'pdf_matches':pdf_agrees,
            'pdf_word_regions':pdf_neighbors,'secondary_word_regions':neighbors,
            'alignment_method':'word_geometry_v2','pdf_artifact_sha256':sha(pdf_path.read_bytes()),
            'score':line['score'],'region_score':line.get('region_score'),
            'status':status,'issues':issues,'engine':result['engine'],'model_manifest':result['models'],
            'render_sha256':result['image_sha256'],'pipeline_version':VERSION,
            'reread_measurement':reread,'reread_provenance':reread_provenance if reread else None,
            'reread_generated_in_generation':generated_reread and reread is not None,
            'reread_state':verdict['reread_state'],
            'reused_source_span_id':line.get('reused_source_span_id'),
            'reused_from_generation':result.get('reused_from_generation'),
            'role':'PAGE_LABEL_CANDIDATE' if bbox[1]>.85 and line['text'].strip().isdigit() else 'TEXT',
            'review_status':'PENDING'}
        save(job,'source_spans',key+f'-{i:04}',value)
        spans.append({'id':sid,'data':value})
    save(job,'page_readings',key,{'pdf_page':page,'evidence_refs':[str(evidence['id'])],
        'span_ids':[r['id'] for r in spans], 'span_count':len(spans),
        'agreed_spans':sum(r['data']['status']=='TEXT_AGREED' for r in spans),
        'review_spans':sum(r['data']['status']!='TEXT_AGREED' for r in spans),
        'ocr_vl_requested_regions':sum(bool(r['data'].get('ocr_vl_measurement')) for r in spans),
        'ocr_vl_skipped_regions':sum(bool(r['data'].get('ocr_vl_routing')) and not r['data']['ocr_vl_routing']['request_ocr'] for r in spans),
        'regional_truncated':result['regional_truncated'],'seconds':result['seconds'],
        'measurement_reused':bool(result.get('reused_from_generation')),
        'reused_from_generation':result.get('reused_from_generation'),
        'reused_reading_id':result.get('reused_reading_id'),
        'render_sha256':result['image_sha256'],'model_manifest':result['models'],
        'status':('NO_TEXT_DETECTED' if not spans else 'NEEDS_REVIEW' if result['regional_truncated'] or any(r['data']['status']!='TEXT_AGREED' for r in spans) else 'TEXT_AGREED'),
        'review_status':'PENDING','pipeline_version':VERSION})


def observe(job,evidence,layout,spans,root,parent=None):
    from editor.analysis import model
    from editor.source_review import speaker_candidates
    from editor.visual_coverage import selected_regions, coverage
    gen=job['generation_id']; page=evidence['data']['pdf_page']; key=evidence['record_key']
    illustrations=selected_regions(layout['data'])
    observations=[]
    if parent:
        prior=next((r for r in get_records(parent,'visual_observations') if r['record_key']==key),None)
        old_evidence=next((r for r in get_records(parent,'evidence') if r['record_key']==key),None)
        if (prior and old_evidence
                and all(same_model(o.get('metrics',{})) for o in prior['data']['observations'])
                and old_evidence['data']['render_sha256']==evidence['data']['render_sha256']):
            value={**prior['data'],'evidence_refs':[str(evidence['id'])],
                'source_span_ids':[str(s['id']) for s in spans],
                'reused_visual_observation_id':str(prior['id']),
                'reused_from_generation':str(parent),'pipeline_version':VERSION}
            value['speaker_links']=speaker_candidates(layout['data'],value)
            value['coverage']=coverage(layout['data'],value['observations'])
            value['omitted_regions']=value['coverage']['unobserved_picture_regions']
            # Keep original metrics and provenance; do not claim a new model call.
            if all(any(o.get('region_bbox')==r['bbox'] for o in value['observations']) for r in illustrations):
                save(job,'visual_observations',key,value)
                return
            observations=[{**o,'reused_visual_observation_id':str(prior['id']),
                           'reused_from_generation':str(parent)} for o in prior['data']['observations']]
    # Every selected region has its own crop; any omitted region is explicit.
    for i,region in enumerate(illustrations):
        if any(o.get('region_bbox')==region['bbox'] for o in observations):
            continue
        raw=(root/f'page-{page:04}.png').read_bytes()
        with httpx.Client(timeout=60,trust_env=False) as client:
            from editor.ocr_vl import crop_request
            response=crop_request(client,{'image_base64':base64.b64encode(raw).decode(),'bbox':region['bbox']})
            response.raise_for_status(); crop=response.json()
        if crop['source_image_sha256']!=evidence['data']['render_sha256']: raise RuntimeError('CROP_SOURCE_MISMATCH')
        prompt=('Yalnız bu kırpılmış resimde görünen figür ve hareket adaylarını kaydet. '
            'Yazıları okuma veya alıntılama, karakter adı verme, hikaye özeti yazma. '
            'JSON {"figures":[{"local_id":"figure_1","appearance":"...","visible_action":"...",'
            '"bbox":[0.0,0.0,0.2,0.2]}],"uncertainties":["..."]}. '
            'bbox kırpım içinde normalize sol üst x,y,genişlik,yükseklik. Gözün açık/kapalı olduğu belirsizse söyle. '
            'Figür yoksa figures boş. En fazla dört figür. Bunlar doğrulanmamış gözlemlerdir.')
        answer,metrics=model([{'role':'user','content':[{'type':'text','text':prompt},
            {'type':'image_url','image_url':{'url':'data:image/png;base64,'+crop['image_base64']}}]}],
            max_tokens=650,prompt_version=VERSION+'-visual-regions')
        figures=[]
        for f in answer.get('figures',[])[:4]:
            box=f.get('bbox',[])
            if not valid_box(box):
                continue
            figures.append({k:f.get(k) for k in ('local_id','appearance','visible_action','bbox')})
        observations.append({'region_bbox':region['bbox'],'crop_sha256':crop['crop_sha256'],
            'figures':figures,'uncertainties':answer.get('uncertainties',[]),'metrics':metrics,
            'figure_coverage':'NOT_VERIFIED',
            'figure_output_limit':4,'figure_limit_reached':len(answer.get('figures',[]))>=4,
            'discarded_figure_candidates':len(answer.get('figures',[]))-len(figures)})
    # No inferred speaker may become a named character without independent grounding.
    save(job,'visual_observations',key,{'pdf_page':page,'evidence_refs':[str(evidence['id'])],
        'observations':observations,'coverage':coverage(layout['data'],observations),
        'omitted_regions':coverage(layout['data'],observations)['unobserved_picture_regions'],
        'speaker_links':speaker_candidates(layout['data'],{'observations':observations}),
        'speaker':'UNKNOWN','speaker_status':'TAIL_AND_CHARACTER_GROUNDING_NOT_VERIFIED',
        'verification_status':'CANDIDATE','eligible_as_claim_source':False,
        'source_span_ids':[str(s['id']) for s in spans], 'pipeline_version':VERSION,
        'review_status':'PENDING'})


def reusable_claim_candidates(parent,key,spans):
    if not parent:
        return None
    prior=next((r for r in get_records(parent,'page_claims') if r['record_key']==key),None)
    if prior is None:
        return None
    if not same_model(prior['data'].get('metrics',{})):
        return None
    old=[r for r in get_records(parent,'source_spans') if r['data']['pdf_page']==int(key)]
    def context(rows):
        return [(r['data']['text'] if r['data']['status']=='TEXT_AGREED' and r['data']['role']=='TEXT' else '[UNVERIFIED_REGION]',
                 r['data']['bbox']) for r in reading_order(rows)]
    previous_context, current_context = context(old), context(spans)
    reuse_policy = 'IDENTICAL_CONTEXT'
    if previous_context != current_context:
        # Tightening a source gate adds no information. Retain the machine's
        # original proposals as proposals, then run every quote/reference gate
        # again below. A removed source can only invalidate a proposal. Never
        # reuse this way when text/geometry changes or any source is promoted.
        before = {r['record_key']: r['data'] for r in old}
        after = {r['record_key']: r['data'] for r in spans}
        if before.keys() != after.keys():
            return None
        for key in before:
            a, b = before[key], after[key]
            if any(a.get(k) != b.get(k) for k in ('text', 'raw_text', 'bbox', 'role', 'render_sha256')):
                return None
            if b['status'] == 'TEXT_AGREED' and a['status'] != 'TEXT_AGREED':
                return None
        if any(c.get('eligible_for_synthesis') is not False
               for c in prior['data']['claims'] + prior['data']['blocked_claims']):
            return None
        reuse_policy = 'UNCHANGED_MEASUREMENTS_STRICTER_SOURCE_GATE'
    new_by_key={r['record_key']:str(r['id']) for r in spans}
    mapping={str(r['id']):new_by_key[r['record_key']] for r in old if r['record_key'] in new_by_key}
    candidates=[]
    for candidate in prior['data']['claims']+prior['data']['blocked_claims']:
        if any(ref not in mapping for ref in candidate.get('span_refs',[])):
            return None
        candidates.append({**candidate,'span_refs':[mapping[ref] for ref in candidate.get('span_refs',[])]})
    return {'page_role':prior['data']['page_role'],'claims':candidates,
            'measurement_reuse_policy':reuse_policy,
            'uncertainties':prior['data']['uncertainties']},prior['data']['metrics'],str(prior['id'])


def interpret(job,evidence,spans,parent=None,page_purpose=None,layout_record=None):
    from editor.analysis import model
    from editor.source_unit_claims import propose, VERSION as UNIT_VERSION
    from editor.text_attribution import extract as text_attributions, speaker_for_claim
    page=evidence['data']['pdf_page']; key=evidence['record_key']
    usable=[s for s in spans if s['data']['status']=='TEXT_AGREED' and s['data']['role']=='TEXT']
    excluded=[str(s['id']) for s in spans if s not in usable]
    # Optical/visual measurements can be reused. Semantic proposals are fresh
    # for this source-unit contract; legacy generated quotations are not reused.
    def fenced_model(*args,**kwargs):
        # Multi-chunk pages must observe cancellation/lease loss between calls,
        # not only after the entire page has finished using the model.
        with connection() as db:fence(db,job)
        response=model(*args,**kwargs)
        with connection() as db:fence(db,job)
        return response
    # Even a page without agreed text gets an explicit, empty coverage ledger.
    # The proposer records per-chunk budget/truncation failures. Unexpected
    # failures must fail the job instead of persisting a false complete ledger.
    result,metrics=propose(page,spans,fenced_model,page_purpose=page_purpose,layout_record=layout_record)
    attribution = text_attributions(spans, result.get('page_role','UNKNOWN'))
    save(job,'character_evidence',key,{'pdf_page':page,
        'evidence_refs':[str(evidence['id'])], 'pipeline_version':VERSION, **attribution})
    allowed={str(s['id']):s for s in usable}; accepted=[]; blocked=[]
    for c in result.get('claims',[]):
        refs=c.get('span_refs',[]); chosen=[allowed[r] for r in refs if r in allowed]
        reason=quote_check(c.get('quote',''),chosen,spans) if refs and len(chosen)==len(refs) else 'INVALID_SPAN_REFERENCE'
        if reason=='MATCH' and bool(negation(c.get('quote',''))) != bool(negation(c.get('text',''))):
            reason='CLAIM_POLARITY_REQUIRES_REVIEW'
        if c.get('kind')=='ENTITY': reason='ENTITY_IDENTITY_REQUIRES_REVIEW'
        reason=narrative_gate(result.get('page_role','UNKNOWN'),reason)
        # Supported transcription is not entailment. Keep all semantic candidates out
        # of accepted facts until semantic and speaker checks exist for that claim.
        speaker = speaker_for_claim(c, attribution['attributions']) if reason=='MATCH' else None
        item={**c,'speaker':speaker['label'] if speaker else None,
            'speaker_status':'EXPLICIT_TEXT_ATTRIBUTION' if speaker else 'UNKNOWN',
            'speaker_source_span_refs':speaker['source_span_refs'] if speaker else [],
            'speaker_method':speaker['method'] if speaker else None,
            'visual_identity_verified':False,
            'source_gate':reason,'verification_status':'TEXT_MATCHED_CANDIDATE' if reason=='MATCH' else 'NEEDS_REVIEW',
            'eligible_for_synthesis':False,'evidence_refs':[str(evidence['id'])]}
        (accepted if reason=='MATCH' else blocked).append(item)
    save(job,'page_claims',key,{'pdf_page':page,'page_role':result.get('page_role','UNKNOWN'),
        'claims':accepted,'blocked_claims':blocked,'excluded_span_ids':excluded,
        'input_span_ids':list(allowed),'input_visual_descriptions':False,
        'reused_claim_candidates_from':None,'candidate_reuse_policy':None,'reused_from_generation':None,
        'source_unit_method':UNIT_VERSION,'source_units':result.get('source_units',[]),
        'proposal_page_purpose':result['proposal_page_purpose'],
        'atomic_balloon_manifest':result['atomic_balloon_manifest'],
        'source_unit_coverage':result.get('source_unit_coverage'),
        'raw_model_result':result.get('raw_model_result'),
        'rejected_model_candidates':result.get('rejected_model_candidates',[]),
        'uncertainties':result.get('uncertainties',[]),'metrics':metrics,'review_status':'PENDING'})
    save(job,'page_checks',key,{'pdf_page':page,'evidence_refs':[str(evidence['id'])],
        'status':'NEEDS_REVIEW','text_matched_candidates':len(accepted),'blocked_claims':len(blocked),
        'source_review_spans':len(excluded),'semantic_acceptance':False,
        'reason':'SEMANTIC_AND_SPEAKER_ACCEPTANCE_PENDING','pipeline_version':VERSION})


def run(job):
    from editor.analysis import ingest
    from editor.page_reuse import resolve_page_parent
    gen=job['generation_id']; source=source_for(gen); root=ROOT/source['sha256']
    with connection() as db:
        fence(db,job)
        previous=db.execute('SELECT manifest FROM editor.generations WHERE id=%s',(gen,)).fetchone()['manifest']
        if previous.get('code_manifest') and previous['code_manifest']!=code_manifest():
            raise RuntimeError('PIPELINE_VERSION_CHANGED_NEW_GENERATION_REQUIRED')
        db.execute('UPDATE editor.generations SET manifest=manifest || %s WHERE id=%s',
            (Jsonb({'pipeline_version':VERSION,'code_manifest':code_manifest(),
                   'old_visual_reuse':False,'processing_order':'page_sources_then_verified_purpose_then_claims',
                   'ocr_vl_model':os.environ.get('EDITOR_OCR_VL_MODEL'),
                   'source_of_quotes':'source_spans_only'}),gen))
    parent=previous.get('reuse_measurements_from')
    if parent and source_for(parent)['content_version_id']!=source['content_version_id']:
        raise RuntimeError('REUSED_CONTENT_VERSION_MISMATCH')
    ingest(job)
    document=json.loads((root/'docling.json').read_text())
    evidence=get_records(gen,'evidence'); done={r['record_key'] for r in get_records(gen,'page_readings')}
    priorities={page:i for i,page in enumerate(previous.get('priority_pages',[]))}
    evidence.sort(key=lambda r:(priorities.get(r['data']['pdf_page'],len(priorities)),r['data']['pdf_page']))
    observed={r['record_key'] for r in get_records(gen,'visual_observations')}
    checked={r['record_key'] for r in get_records(gen,'page_checks')}
    for row in evidence:
        with connection() as db: fence(db,job)
        page_parent=resolve_page_parent(parent,row['record_key'],source['content_version_id'])
        from concurrent.futures import ThreadPoolExecutor
        # Only independent image observation overlaps OCR. Claims wait for both.
        with ThreadPoolExecutor(max_workers=1) as pool:
            visual_future=None
            def on_layout(layout,pending_spans):
                nonlocal visual_future
                if row['record_key'] not in observed:
                    visual_future=pool.submit(observe,job,row,layout,pending_spans,root,page_parent)
            if row['record_key'] not in done:
                optical(job,row,document,root,page_parent,on_layout=on_layout)
            if visual_future is not None:
                visual_future.result()
                observed.add(row['record_key'])
        layouts={r['record_key']:r for r in get_records(gen,'layout_regions')}
        all_spans=get_records(gen,'source_spans')
        spans=[s for s in all_spans if s['data']['pdf_page']==row['data']['pdf_page']]
        if row['record_key'] not in observed: observe(job,row,layouts[row['record_key']],spans,root,page_parent)
    from editor.source_fragments import run as resolve_fragments
    resolve_fragments(job,root)
    from editor.page_context import run as resolve_page_context
    resolve_page_context(job)
    # Candidate extraction consumes the separately checked source purpose. A
    # short balloon question must not independently redefine its page as an
    # exercise before the neighbouring source context has been considered.
    from editor.page_context import story_authority
    contexts={r['data']['pdf_page']:r for r in get_records(gen,'page_context_roles')}
    layout_records={r['data']['pdf_page']:r for r in get_records(gen,'layout_regions')}
    all_spans=get_records(gen,'source_spans')
    fragments=get_records(gen,'source_fragments')
    layouts={r['data']['pdf_page']:r['data'] for r in get_records(gen,'layout_regions')}
    bundles=[{'evidence':row,'layout':layouts[row['data']['pdf_page']],
              'spans':[s for s in all_spans if s['data']['pdf_page']==row['data']['pdf_page']],
              'fragments':[s for s in fragments if s['data']['pdf_page']==row['data']['pdf_page']]}
             for row in sorted(evidence,key=lambda r:r['record_key'])]
    for row in evidence:
        if row['record_key'] in checked:continue
        page=row['data']['pdf_page']
        purpose=story_authority(page,bundles,contexts.get(page))
        interpret(job,row,[s for s in all_spans if s['data']['pdf_page']==page],page_purpose=purpose,layout_record=layout_records[page])
    from editor.figure_identity import run as resolve_figures
    from editor.semantic_acceptance import run as review_semantics
    # Both consume immutable page sources. Neither promotes the other's model
    # opinion into identity evidence or whole-book editorial approval.
    with ThreadPoolExecutor(max_workers=2) as pool:
        identity_future=pool.submit(resolve_figures,job,root)
        semantic_future=pool.submit(review_semantics,job)
        identity_future.result()
        semantic_future.result()
    with connection() as db:
        fence(db,job)
        db.execute("UPDATE editor.jobs SET status='COMPLETED',finished_at=now(),progress=%s WHERE id=%s",
            (Jsonb({'stage':'source_analysis','status':'NEEDS_REVIEW','completed_pages':len(evidence),
                    'identity_and_semantic_pass_finished':True,'semantic_acceptance':False}),job['id']))
        db.execute("UPDATE editor.generations SET status='NEEDS_REVIEW' WHERE id=%s",(gen,))
