relationships:
  - name: "Dbo.lg_411_01_invoiceClientrefDbo.lg_411_clcardLogicalref"
    models:
      - "dbo_LG_411_01_INVOICE"
      - "dbo_LG_411_CLCARD"
    join_type: MANY_TO_ONE
    condition: "\"dbo_LG_411_01_INVOICE\".CLIENTREF = \"dbo_LG_411_CLCARD\".LOGICALREF"
  - name: "Dbo.lg_411_01_stlineInvoicerefDbo.lg_411_01_invoiceLogicalref"
    models:
      - "dbo_LG_411_01_STLINE"
      - "dbo_LG_411_01_INVOICE"
    join_type: MANY_TO_ONE
    condition: "\"dbo_LG_411_01_STLINE\".INVOICEREF = \"dbo_LG_411_01_INVOICE\".LOGICALREF"
  - name: "Dbo.lg_411_01_stlineStockrefDbo.lg_411_itemsLogicalref"
    models:
      - "dbo_LG_411_01_STLINE"
      - "dbo_LG_411_ITEMS"
    join_type: MANY_TO_ONE
    condition: "\"dbo_LG_411_01_STLINE\".STOCKREF = \"dbo_LG_411_ITEMS\".LOGICALREF"
  - name: "Dbo.lg_411_01_stlineClientrefDbo.lg_411_clcardLogicalref"
    models:
      - "dbo_LG_411_01_STLINE"
      - "dbo_LG_411_CLCARD"
    join_type: MANY_TO_ONE
    condition: "\"dbo_LG_411_01_STLINE\".CLIENTREF = \"dbo_LG_411_CLCARD\".LOGICALREF"
  - name: "Dbo.lg_411_01_orflineOrdficherefDbo.lg_411_01_orficheLogicalref"
    models:
      - "dbo_LG_411_01_ORFLINE"
      - "dbo_LG_411_01_ORFICHE"
    join_type: MANY_TO_ONE
    condition: "\"dbo_LG_411_01_ORFLINE\".ORDFICHEREF = \"dbo_LG_411_01_ORFICHE\".LOGICALREF"
  - name: "Dbo.lg_411_01_orflineStockrefDbo.lg_411_itemsLogicalref"
    models:
      - "dbo_LG_411_01_ORFLINE"
      - "dbo_LG_411_ITEMS"
    join_type: MANY_TO_ONE
    condition: "\"dbo_LG_411_01_ORFLINE\".STOCKREF = \"dbo_LG_411_ITEMS\".LOGICALREF"
  - name: "Dbo.lg_411_01_orficheClientrefDbo.lg_411_clcardLogicalref"
    models:
      - "dbo_LG_411_01_ORFICHE"
      - "dbo_LG_411_CLCARD"
    join_type: MANY_TO_ONE
    condition: "\"dbo_LG_411_01_ORFICHE\".CLIENTREF = \"dbo_LG_411_CLCARD\".LOGICALREF"
  - name: "Dbo.lg_411_01_clflineClientrefDbo.lg_411_clcardLogicalref"
    models:
      - "dbo_LG_411_01_CLFLINE"
      - "dbo_LG_411_CLCARD"
    join_type: MANY_TO_ONE
    condition: "\"dbo_LG_411_01_CLFLINE\".CLIENTREF = \"dbo_LG_411_CLCARD\".LOGICALREF"
