#!/usr/bin/env python3
"""Üst kaynaktan alınan Helpdesk ve Flow kodunu NanobaseAI markasına çevirir.

Tekrar koşturulabilir: her düzeltme ya uygulanır ya da zaten uygulanmıştır.
Eski metin de yeni metin de bulunamazsa üst kaynak değişmiştir; betik durur ve
hangi dosyada neyi bulamadığını yazar — o satır elle yeniden yazılır.

Kullanım (depo kökünden):
    python3 apps/destek/tools/marka.py           # uygula
    python3 apps/destek/tools/marka.py --denetle # yalnız kalan marka izlerini say

Kapsam: ekranda, hata/bilgi mesajında, e-postada ve PWA bildiriminde görünen
ürün/marka adları. Kod içi sınıf/modül adları (HelpdeskSearch, "module": "Flow"),
lisans başlıkları ve veritabanı adları değişmez — değişirse kurulu sitelerin
göçü bozulur. DocType adları (Flow Agent, HD Ticket…) ekranda çeviriyle
değişir: nanobase_brand/locale/tr.po.
"""

from __future__ import annotations

import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
APPS = ROOT / "frappe-apps"
MARKA = ROOT / "marka"
BRAND = "NanobaseAI"

WELCOME = '''
<div style="font-family: 'DM Sans', 'Segoe UI', sans-serif; font-size: 15px; line-height: 1.8; color: #1b1f2a; max-width: 560px; margin: 0 auto;">
Merhaba{{ " " + first_name if first_name else "" }},
<br><br>
Bu örnek kayıt, NanobaseAI destek ekranının nasıl çalıştığını göstermek için oluşturuldu.
<br><br>
<b>Etkinlik alanı:</b> kayda verdiğiniz her yanıt hemen altta, kaydın geçmişinde görünür; bütün yazışma tek yerde durur.
<br><br>
<b>Yanıtla</b> dediğinizde mesajınız doğrudan kişinin e-posta kutusuna gider.
<br><br>
<b>Yorum</b> yalnız ekip arkadaşlarınızın gördüğü iç nottur; müşteriye gitmez.
<br><br>
<b>Kayıt kenar çubuğunda</b> kaydı kendinize ya da bir arkadaşınıza atar, önceliği, türü ve durumu değiştirirsiniz.
<br><br>
<b>Kayıt başlığında</b> ilk yanıt ve çözüm süreleri ile kaydın nereden geldiği (e-posta ya da destek portalı) görünür.
<br><br>
Sonraki adımlar:<br>
<ul style="padding-left: 20px; margin: 0;">
  <li>Destek e-posta adresinizi bağlayın; gerçek kayıtlar gelmeye başlasın.</li>
  <li>Ekibinizi davet edin, atama kurallarıyla kayıtları otomatik dağıtın.</li>
  <li>Yanıt sürelerini yönetmek için hizmet seviyesi (SLA) tanımlayın.</li>
  <li>Kendi kendine yardım için bilgi bankası makaleleri ekleyin.</li>
</ul>
<br>
NanobaseAI
</div>
'''

# (dosya, [(eski, yeni), ...]) — eski birebir aranır.
EDITS: list[tuple[str, list[tuple[str, str]]]] = [
	# ── Helpdesk arka uç ──────────────────────────────────────────────────
	(
		"helpdesk/helpdesk/hooks.py",
		[
			('app_title = "Helpdesk"', f'app_title = "{BRAND}"'),
			('        "logo": "/assets/helpdesk/desk/favicon.svg",\n        "title": "Helpdesk",',
			 f'        "logo": "/assets/helpdesk/desk/favicon.svg",\n        "title": "{BRAND}",'),
		],
	),
	("helpdesk/helpdesk/config/docs.py", [('context.brand_html = "Frappe Helpdesk"', f'context.brand_html = "{BRAND}"')]),
	(
		"helpdesk/helpdesk/setup/install.py",
		[('"Autogenerated field by Helpdesk App"', f'"Autogenerated field by {BRAND}"')],
	),
	("helpdesk/helpdesk/templates/emails/macros.html", [("  Team Frappe", f"  {BRAND}"), ("  Thanks,<br />", "  Teşekkürler,<br />")]),
	(
		"helpdesk/helpdesk/setup/welcome_ticket.py",
		[
			('AUTHOR_EMAIl = "john@example.com"\nAUTHOR_NAME = "John Doe"',
			 'AUTHOR_EMAIl = "ornek.musteri@example.com"\nAUTHOR_NAME = "Örnek Müşteri"'),
			('d.subject = "Welcome to Helpdesk"', 'd.subject = "NanobaseAI\'ye hoş geldiniz"'),
			('first_name = "there"\n    else:\n        first_name = (user_doc.first_name or "").strip() or "there"',
			 'first_name = ""\n    else:\n        first_name = (user_doc.first_name or "").strip()'),
		],
	),
	(
		"helpdesk/helpdesk/api/onboarding.py",
		[
			('{"subject": "Welcome to Helpdesk"}', '{"subject": "NanobaseAI\'ye hoş geldiniz"}'),
			('"subject": ["!=", "Welcome to Helpdesk"]', '"subject": ["!=", "NanobaseAI\'ye hoş geldiniz"]'),
		],
	),
	(
		"helpdesk/helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py",
		[('if self.subject == "Welcome to Helpdesk":', 'if self.subject == "NanobaseAI\'ye hoş geldiniz":')],
	),
	(
		"helpdesk/helpdesk/helpdesk/workspace/helpdesk/helpdesk.json",
		[('Visit Helpdesk</a>', f'{BRAND} destek ekranı</a>')],
	),
	# ── Helpdesk ön yüz ───────────────────────────────────────────────────
	(
		"helpdesk/desk/index.html",
		[
			("<title>Helpdesk</title>", f"<title>{BRAND}</title>"),
			('content="Frappe Helpdesk"', f'content="{BRAND}"'),
			('    <meta name="apple-mobile-web-app-status-bar-style" content="white" />',
			 '    <meta name="apple-mobile-web-app-status-bar-style" content="white" />\n'
			 '    <link rel="preconnect" href="https://fonts.googleapis.com" />\n'
			 '    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />\n'
			 '    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,400;9..40,500;9..40,600;9..40,700&family=Plus+Jakarta+Sans:wght@600;700;800&display=swap" />'),
		],
	),
	(
		"helpdesk/desk/vite.config.js",
		[
			('name: "Frappe Helpdesk",\n          short_name: "Helpdesk",', f'name: "{BRAND}",\n          short_name: "{BRAND}",'),
			('"Modern, Streamlined, Free and Open Source Customer Service Software"', '"NanobaseAI müşteri destek ekranı"'),
		],
	),
	(
		"helpdesk/desk/src/index.css",
		[('@import "frappe-ui/editor-style.css";', '@import "frappe-ui/editor-style.css";\n@import "./nanobase-theme.css";')],
	),
	("helpdesk/desk/src/components/UserMenu.vue", [('config.brandName || "Helpdesk"', f'config.brandName || "{BRAND}"')]),
	(
		"helpdesk/desk/src/components/Settings/Preferences/Preferences.vue",
		[(":name=\"config.brandName || 'Helpdesk'\"", f":name=\"config.brandName || '{BRAND}'\"")],
	),
	(
		"helpdesk/desk/src/components/Questionnaire.vue",
		[('"This helps us personalize your Helpdesk experience."', f'"This helps us personalize your {BRAND} experience."')],
	),
	(
		"helpdesk/desk/src/components/Settings/InviteAgents.vue",
		[('__("Can manage all aspects of Helpdesk.")', f'__("Can manage all aspects of {BRAND}.")')],
	),
	(
		"helpdesk/desk/src/components/Settings/Telephony/ExotelSettings.vue",
		[("'Configure your Exotel settings for Helpdesk.'", f"'Configure your Exotel settings for {BRAND}.'")],
	),
	(
		"helpdesk/desk/src/components/Settings/Telephony/TwilioSettings.vue",
		[("'Configure your Twilio settings for Helpdesk.'", f"'Configure your Twilio settings for {BRAND}.'")],
	),
	("helpdesk/desk/src/pages/ticket/TicketCustomer.vue", [('document.title = "Helpdesk";', f'document.title = "{BRAND}";')]),
	("helpdesk/desk/src/pages/ticket/MobileTicketAgent.vue", [('document.title = "Helpdesk";', f'document.title = "{BRAND}";')]),
	(
		"helpdesk/desk/src/components/customer/NewCustomerDialog.vue",
		[('placeholder="Frappe"', 'placeholder="Örnek A.Ş."'), ('placeholder="frappe.io"', 'placeholder="ornek.com.tr"')],
	),
	("helpdesk/desk/src/composables/customer.ts", [('placeholder: "frappe.io",', 'placeholder: "ornek.com.tr",')]),
	("helpdesk/desk/src/composables/useApps.ts", [('logo: "/assets/helpdesk/desk/desk.png",', 'logo: "/assets/helpdesk/desk/favicon.svg",')]),
	(
		"helpdesk/desk/src/components/layouts/Sidebar.vue",
		[
			('    title="Frappe Helpdesk"\n    :logo="logo"\n    docsLink="https://docs.frappe.io/helpdesk"',
			 f'    title="{BRAND}"\n    :logo="logo"\n    docsLink=""'),
			# Dışarıya (üreticinin destek kanalı, belgeleri, bulut hesabı) giden menü satırları çıkar.
			('  {\n    icon: "lucide-life-buoy",\n    label: __("Support"),\n    onClick: () => window.open("https://t.me/frappedesk"),\n  },\n'
			 '  {\n    icon: "lucide-book-open",\n    label: __("Docs"),\n    onClick: () => window.open("https://docs.frappe.io/helpdesk"),\n  },\n'
			 '  {\n    label: __("Login to Frappe Cloud"),\n    icon: FrappeCloudIcon,\n    onClick: () => confirmLoginToFrappeCloud(),\n    condition: () => !isMobileView.value && window.is_fc_site,\n  },\n',
			 ''),
		],
	),
	(
		"helpdesk/desk/src/components/layouts/MobileSidebar.vue",
		[
			('  {\n    icon: "lucide-life-buoy",\n    label: __("Support"),\n    onClick: () => window.open("https://t.me/frappedesk"),\n  },\n'
			 '  {\n    icon: "lucide-book-open",\n    label: __("Docs"),\n    onClick: () => window.open("https://docs.frappe.io/helpdesk"),\n  },\n',
			 ''),
		],
	),
	(
		"helpdesk/desk/src/pages/PersonaForm.vue",
		[
			('"How would you like your customers to create support tickets in Frappe Helpdesk?"',
			 f'"How would you like your customers to create support tickets in {BRAND}?"'),
			('title: __("What would you like to do first in Frappe Helpdesk?"),', f'title: __("What would you like to do first in {BRAND}?"),'),
			('usePageMeta(() => ({ title: __("Welcome to Frappe Helpdesk") }));', f'usePageMeta(() => ({{ title: __("Welcome to {BRAND}") }}));'),
			('title: __("How did you hear about Frappe Helpdesk?"),', f'title: __("How did you hear about {BRAND}?"),'),
			('      { label: __("Frappe Discuss"), value: "frappe_discuss" },\n'
			 '      {\n        label: __("Another Frappe product (ERPNext, Frappe Cloud, etc.)"),\n        value: "frappe_product",\n      },\n',
			 ''),
			('      { label: __("A Frappe partner or consultant"), value: "partner" },\n', '      { label: __("A partner or consultant"), value: "partner" },\n'),
		],
	),
	(
		# Üreticinin kendi posta hizmeti seçenek listesinden çıkar; kayıtlı hesap varsa düzenleme ekranı hâlâ açar.
		"helpdesk/desk/src/components/Settings/emailConfig.ts",
		[
			('  {\n    name: "Frappe Mail",\n    icon: LogoFrappeMail,\n    info: __(\n'
			 '      `Setting up Frappe Mail requires you to have an API key and API Secret of your email account. Read more`\n'
			 '    ),\n    link: "https://github.com/frappe/mail",\n    custom: true,\n  },\n',
			 ''),
			('label: __("Frappe Mail site"),', 'label: __("Mail site"),'),
		],
	),
	(
		# ERPNext eşitleme sekmesi ayarlardan gizlenir (bu kurulumda kayıt sistemi Logo'dur).
		"helpdesk/desk/src/components/Settings/settingsModal.ts",
		[('          component: markRaw(ERPNextIntegrationSettings),\n          condition: () => auth.isAdmin || auth.isManager,',
		  '          component: markRaw(ERPNextIntegrationSettings),\n          condition: () => false,')],
	),
	# ── Dış bağlantılar: üretici belgeleri, sağlayıcı yardım sayfaları (kullanıcı kararı 2026-09-28: tamamen silinir) ──
	(
		"helpdesk/desk/src/components/Settings/Sla/SlaPolicies.vue",
		[('            "SLAs align your team and customers with defined timelines for a reliable experience. Learn more about SLA "\n'
		  '          )\n        }}\n        <a\n          href="https://docs.frappe.io/helpdesk/service-level-agreement"\n'
		  '          target="_blank"\n          class="underline"\n          >{{ __("here.") }}\n        </a>',
		  '            "SLAs align your team and customers with defined timelines for a reliable experience."\n'
		  '          )\n        }}')],
	),
	(
		"helpdesk/desk/src/components/Settings/FieldDependency/FieldDependencyList.vue",
		[('            "Create field dependencies to dynamically update options based on user selections. Learn more about field dependencies"\n'
		  '          )\n        }}\n        <a\n          href="https://docs.frappe.io/helpdesk/field-dependency"\n'
		  '          target="_blank"\n          class="underline"\n          >{{ __("here.") }}</a\n        >',
		  '            "Create field dependencies to dynamically update options based on user selections."\n'
		  '          )\n        }}')],
	),
	(
		"helpdesk/desk/src/components/Settings/Assignment Rules/AssignmentRuleView.vue",
		[('                <a\n                  class="font-medium underline"\n                  href="https://docs.frappe.io/helpdesk/assignment-rule"\n'
		  '                  target="_blank"\n                  >{{ __("Learn about conditions") }}</a\n                >\n', '')],
	),
	(
		"helpdesk/desk/src/components/Settings/General/components/TicketSettings.vue",
		[('            {{\n              __(\n                "Find out all of the variables that can be used in the content"\n              )\n            }}\n'
		  '            <a\n              href="https://docs.frappe.io/helpdesk/helpdesk/customization/outside-working-hours-banner"\n'
		  '              target="_blank"\n              class="underline font-semibold"\n              >{{ __("here") }}</a\n            >\n', '')],
	),
	(
		"helpdesk/desk/src/components/Settings/EmailNotifications/Notification.vue",
		[('                {{\n                  __(\n                    "Find out all of the variables that can be used in the content"\n                  )\n                }}\n'
		  '                <a\n                  :href="props.documentationLink"\n                  target="_blank"\n                  class="underline font-semibold"\n'
		  '                  >{{ __("here") }}</a\n                >\n', '')],
	),
	(
		"helpdesk/desk/src/components/layouts/CustomerPortalPermissionDialog.vue",
		[('          {{ __("Learn more in the") }}\n          <a\n            href="https://docs.frappe.io/helpdesk/customers-contacts#update-on-permissions"\n'
		  '            target="_blank"\n            class="underline"\n            >{{ __("documentation") }}</a\n          >.\n', '')],
	),
	(
		"helpdesk/desk/src/components/Settings/SavedReplies/SavedReplyView.vue",
		[('            <DocumentationButton\n              url="https://docs.frappe.io/helpdesk/saved-replies"\n            />\n', '')],
	),
	(
		"helpdesk/desk/src/components/Settings/FieldDependency/FieldDependencyCriteria.vue",
		[('            <DocumentationButton\n              url="https://docs.frappe.io/helpdesk/field-dependency#handling-visibility-of-child-field"\n'
		  '              color="!text-ink-gray-6"\n            />\n', ''),
		 ('            <DocumentationButton\n              url="https://docs.frappe.io/helpdesk/field-dependency#handling-if-the-child-field-is-mandatory"\n'
		  '              color="!text-ink-gray-6"\n            />\n', '')],
	),
	(
		"helpdesk/desk/src/components/Settings/EmailEdit.vue",
		[('              <span>\n                {{ info.description }}\n                <a\n                  :href="info.link"\n'
		  '                  target="_blank"\n                  class="text-ink-blue-5 underline"\n                  >here</a\n                >.\n              </span>\n', ''),
		 ('  link: "https://docs.frappe.io/erpnext/user/manual/en/email-domain",\n', '  link: "",\n')],
	),
	(
		# Sağlayıcı yardım sayfaları: bağlantı boşaltılır, «Read more» metinden çıkar, bağlantı yalnız iç adreste görünür.
		"helpdesk/desk/src/components/Settings/EmailAdd.vue",
		[('                  {{ selectedService.info }}\n                  <a\n                    :href="selectedService.link"\n',
		  '                  {{ selectedService.info }}\n                  <a\n                    v-if="selectedService.link"\n                    :href="selectedService.link"\n'),
		 ('                    >here</a\n                  >\n                  .\n', '                    >here</a\n                  >\n')],
	),
	(
		"helpdesk/desk/src/components/Settings/emailConfig.ts",
		[(' Read more`),\n    link: "https://support.google.com/accounts/answer/185833",', '`),\n    link: "",'),
		 (' Read more`),\n    link: "https://support.microsoft.com/en-us/account-billing/how-to-get-and-use-app-passwords-5896ed9b-4263-e681-128a-a6f2979a7944",', '`),\n    link: "",'),
		 (' Read more`),\n    link: "https://sendgrid.com/docs/ui/account-and-settings/two-factor-authentication/",', '`),\n    link: "",'),
		 (' Read more`),\n    link: "https://support.sparkpost.com/docs/my-account-and-profile/enabling-two-factor-authentication",', '`),\n    link: "",'),
		 (' Read more`),\n    link: "https://help.yahoo.com/kb/SLN15241.html",', '`),\n    link: "",'),
		 (' Read more`),\n    link: "https://yandex.com/support/id/authorization/app-passwords.html",', '`),\n    link: "",'),
		 ('placeholder: "https://frappemail.com",', 'placeholder: "https://posta.ornek.com.tr",')],
	),
	(
		# Kurulum rehberindeki yardım merkezi yalnız üretici belge makalelerini açıyordu: menü satırı ve makale listesi çıkar.
		"helpdesk/desk/src/components/layouts/Sidebar.vue",
		[('      <SidebarItem\n        v-if="isOnboardingStepsCompleted && !isCustomerPortal"\n        :label="__(\'Help\')"\n',
		  '      <SidebarItem\n        v-if="false"\n        :label="__(\'Help\')"\n')],
	),
	(
		"helpdesk/desk/src/components/erpnext-integration/ERPNextIntegrationSettings.vue",
		[('              href="https://frappe.io/cloud/install"', '              href="#"')],
	),
	(
		"helpdesk/desk/src/components/Settings/EmailNotifications/Acknowledgement.vue",
		[('documentationLink="https://docs.frappe.io/helpdesk/email-notifications#available-variables-acknowledgement"', 'documentationLink=""')],
	),
	(
		"helpdesk/desk/src/components/Settings/EmailNotifications/ReplyToAgents.vue",
		[('documentationLink="https://docs.frappe.io/helpdesk/email-notifications#available-variables-reply-from-contact"', 'documentationLink=""')],
	),
	(
		"helpdesk/desk/src/components/Settings/EmailNotifications/ReplyViaAgent.vue",
		[('documentationLink="https://docs.frappe.io/helpdesk/email-notifications#available-variables-reply-from-agent"', 'documentationLink=""')],
	),
	(
		"helpdesk/desk/src/components/Settings/EmailNotifications/ShareFeedback.vue",
		[('documentationLink="https://docs.frappe.io/helpdesk/email-notifications#available-variables-share-feedback"', 'documentationLink=""')],
	),
	(
		# Canlı bildirim: sayfa standart dışı portta açılınca (portal.nanobase.ai:8446) üst kaynak geliştirme
		# sunucusu sanıp http://…:9000'e gidiyordu (karışık içerik, engellenir). Masaüstü gibi sayfanın kökü:
		# ters vekil /socket.io'yu websocket servisine taşır.
		"helpdesk/desk/src/socket.ts",
		[('  let host = window.location.hostname;\n  let siteName = window.site_name || host;\n'
		  '  let port = window.location.port ? `:${socketio_port}` : "";\n  let protocol = port ? "http" : "https";\n'
		  '  let url = `${protocol}://${host}${port}/${siteName}`;\n',
		  '  const siteName = window.site_name || window.location.hostname;\n'
		  '  const url = `${window.location.origin}/${siteName}`;\n'),
		 ('import { socketio_port } from "../../../../sites/common_site_config.json";\n', '')],
	),
	(
		# Temsilci ekranı: «NanobaseAI» bölümü (sınıflama, özet, yanıt taslağı, makale taslağı) — bileşen bizim:
		# helpdesk/desk/src/components/ticket-agent/NanobaseAIPanel.vue, arka uç nanobase_brand/yz/kayit.py.
		"helpdesk/desk/src/components/ticket-agent/TicketDetailsTab.vue",
		[('        <!-- Key Info (core fields) -->\n', '        <NanobaseAIPanel />\n\n        <!-- Key Info (core fields) -->\n'),
		 ('import TicketSLA from "./TicketSLA.vue";\n', 'import TicketSLA from "./TicketSLA.vue";\nimport NanobaseAIPanel from "./NanobaseAIPanel.vue";\n')],
	),
	(
		# Üst kaynak hatası (marka değil): artımlı eşitleme, son eşitlemeden sonra silinen belge adlarını bilgi
		# bankasından siliyordu; aynı adla yeniden açılmış (hâlâ var olan) kaydın parçası da gidiyordu.
		"flow/flow/knowledge/ingest.py",
		[('			pluck="deleted_name",\n		)\n	)\n	to_remove = exits | deleted\n',
		  '			pluck="deleted_name",\n		)\n	)\n'
		  '	if deleted:\n'
		  '		deleted -= set(frappe.get_all(ref, filters={"name": ["in", list(deleted)]}, pluck="name"))\n'
		  '	to_remove = exits | deleted\n')],
	),
	# ── Türkçe: üst kaynakta çeviriden geçmeyen kayıt ekranı metinleri (__ ile sarılır; Türkçesi tr.po'da) ──
	(
		'helpdesk/desk/src/components/ticket-agent/TicketActivityPanel.vue',
		[
		 ('import CommunicationArea from "@/components/CommunicationArea.vue";\n', 'import CommunicationArea from "@/components/CommunicationArea.vue";\nimport { __ } from "@/translation";\n'),
		 ('      label: "Activity",\n', '      label: __("Activity"),\n'),
		 ('      label: "Emails",\n', '      label: __("Emails"),\n'),
		 ('      label: "Comments",\n', '      label: __("Comments"),\n'),
		 ('      label: "Calls",\n', '      label: __("Calls"),\n'),
		 ('    label: "Analytics",\n', '    label: __("Analytics"),\n'),
		],
	),
	(
		'helpdesk/desk/src/components/ticket-agent/TicketDetailsTab.vue',
		[
		 ('      `Set ${fieldMeta?.label || fieldTemplate.fieldname}...`,\n', '      __("Set {0}...", [__(fieldMeta?.label || fieldTemplate.fieldname)]),\n'),
		],
	),
	(
		'helpdesk/desk/src/components/ticket-agent/TicketSLA.vue',
		[
		 ('rows.push({ label: "Due by", value:', 'rows.push({ label: __("Due by"), value:'),
		 ('      label: "On hold since",\n', '      label: __("On hold since"),\n'),
		 ('      label: metric.delayInWorkingHours ? "Delay (working hours)" : "Delay",\n', '      label: metric.delayInWorkingHours ? __("Delay (working hours)") : __("Delay"),\n'),
		 ('        label: "Delay (total)",\n', '        label: __("Delay (total)"),\n'),
		 ('      label: "Fulfilled in",\n', '      label: __("Fulfilled in"),\n'),
		],
	),
	(
		'helpdesk/desk/src/composables/useSLA.ts',
		[
		 ('import { dayjs } from "frappe-ui";\n', 'import { dayjs } from "frappe-ui";\nimport { __ } from "@/translation";\n'),
		 ('        `Due in ${coarseDuration(d.response_by)}`,\n', '        __("Due in {0}", [coarseDuration(d.response_by)]),\n'),
		 ('        `Due in ${coarseDuration(d.resolution_by)}`,\n', '        __("Due in {0}", [coarseDuration(d.resolution_by)]),\n'),
		 ('metric("overdue", `Overdue by ${overdue}`, "red", {', 'metric("overdue", __("Overdue by {0}", [overdue]), "red", {'),
		 ('metric("hold", "On Hold", "blue", {', 'metric("hold", __("On Hold"), "blue", {'),
		 ('metric("failed", `Failed by ${failed}`, "red", {', 'metric("failed", __("Failed by {0}", [failed]), "red", {'),
		],
	),
	(
		'helpdesk/desk/src/components/CommunicationArea.vue',
		[
		 ('          label="Reply"\n', '          :label="__(\'Reply\')"\n'),
		 ('          label="Comment"\n', '          :label="__(\'Comment\')"\n'),
		 ("              isMobileView ? 'Send' : isMac ? 'Send (⌘ + ⏎)' : 'Send (Ctrl + ⏎)'\n", "              isMobileView ? __('Send') : isMac ? __('Send') + ' (⌘ + ⏎)' : __('Send') + ' (Ctrl + ⏎)'\n"),
		 ('            placeholder="Hi John, we are looking into this issue."\n', '            :placeholder="__(\'Hi John, we are looking into this issue.\')"\n'),
		],
	),
	(
		'helpdesk/desk/src/components/EmailEditor.vue',
		[
		 ('            <Button label="Discard" @click="handleDiscard" />\n', '            <Button :label="__(\'Discard\')" @click="handleDiscard" />\n'),
		],
	),
	(
		'helpdesk/desk/src/components/CommentTextEditor.vue',
		[
		 ('                label="Discard"\n', '                :label="__(\'Discard\')"\n'),
		],
	),
	# ── Flow ──────────────────────────────────────────────────────────────
	(
		"flow/flow/hooks.py",
		[
			('app_title = "Flow"', f'app_title = "{BRAND}"'),
			('app_description = "Frappe Flow — native AI agents, tools, and triggers for Frappe"',
			 f'app_description = "{BRAND} yapay zekâ ajanları, araçları ve tetikleyicileri"'),
		],
	),
	(
		"flow/flow/assistant/assistant.py",
		[
			('ASSISTANT_AGENT_TITLE = "Flow"', f'ASSISTANT_AGENT_TITLE = "{BRAND}"'),
			('"You are a Frappe assistant operating a live Frappe site through tools. Everything in Frappe "',
			 f'"You are {BRAND}, the assistant of this live {BRAND} workspace, operating it through tools. "\n'
			 f'\t"IDENTITY: you and this platform are {BRAND}. Never name the underlying framework, product, "\n'
			 '\t"model or vendor; if asked what you are or what you run on, say you are ' + BRAND + '. "\n'
			 '\t"Reply in the user\'s language (Turkish when they write Turkish).\\n\\n"\n'
			 '\t"Everything in this workspace "'),
			('"create, update, delete, run_action) already cover all standard Frappe work: reading, writing, "',
			 '"create, update, delete, run_action) already cover all standard work: reading, writing, "'),
			('"STYLE: before each tool call, write one short sentence on what you\'re doing and why — never call a "',
			 '"AUDIENCE: the user is a business person, not a developer. In every sentence they see, never "\n'
			 '\t"write DocType, field or tool names or English system terms; say what you look at in plain "\n'
			 '\t"words (\'destek kayıtlarına bakıyorum\', not \'HD Ticket DocType\').\\n\\n"\n'
			 '\t"STYLE: before each tool call, write one short sentence on what you\'re doing and why — never call a "'),
		],
	),
	("flow/frontend/src/store.js", [('a.find((x) => x.name === "Flow")', f'a.find((x) => x.name === "{BRAND}")')]),
	("flow/frontend/src/main.js", [('__("Toggle Flow panel")', f'__("Toggle {BRAND} panel")')]),
	("flow/frontend/src/components/PanelHeader.vue", [('{{ __("Flow") }}', f'{{{{ __("{BRAND}") }}}}')]),
	("flow/frontend/src/components/EmptyState.vue", [('{{ __("Flow") }}', f'{{{{ __("{BRAND}") }}}}')]),
	(
		"flow/frontend/src/index.css",
		[
			('@import "./styles/markdown.css";', '@import "./styles/markdown.css";\n@import "./styles/nanobase.css";'),
			('\tfont-family: "Inter", "InterVariable", ui-sans-serif, system-ui, sans-serif;',
			 '\tfont-family: "DM Sans", "Inter", "InterVariable", ui-sans-serif, system-ui, sans-serif;'),
		],
	),
]

# Tüm metni değiştirilen bloklar: (dosya, desen, yeni metin)
BLOCKS: list[tuple[str, str, str]] = [
	("helpdesk/desk/src/components/layouts/Sidebar.vue", r"const articles = ref\(\[\n  \{.*?\n\]\);", "const articles = ref([]);"),
	("helpdesk/helpdesk/setup/welcome_ticket.py", r'CONTENT = """.*?"""', 'CONTENT = """' + WELCOME + '"""'),
]

LOGO_MARK = (MARKA / "logo-mark.svg").read_text()
_MARK_BODY = LOGO_MARK[LOGO_MARK.index("<defs>") : LOGO_MARK.index("</svg>")].strip()

HD_LOGO_VUE = f"""<template>
  <svg
    width="118"
    height="118"
    viewBox="0 0 118 118"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    role="img"
    aria-label="{BRAND}"
  >
    {_MARK_BODY}
  </svg>
</template>
"""

FLOW_BRAND_MARK_VUE = f"""<script setup>
defineProps({{ size: {{ type: Number, default: 18 }} }});
</script>

<template>
	<svg
		:width="size"
		:height="size"
		viewBox="0 0 118 118"
		class="shrink-0"
		role="img"
		aria-label="{BRAND}"
	>
		{_MARK_BODY.replace('id="nb-g"', 'id="nb-flow-g"').replace("url(#nb-g)", "url(#nb-flow-g)")}
	</svg>
</template>
"""

# Bütün dosya yazılanlar
WRITES: list[tuple[str, str]] = [
	("helpdesk/desk/src/assets/logos/HDLogo.vue", HD_LOGO_VUE),
	("flow/frontend/src/components/BrandMark.vue", FLOW_BRAND_MARK_VUE),
]

# Dosyanın sonuna eklenenler (zaten varsa atlanır). frappe-ui yaması (patch-package; sürüm yama dosyasının
# adında): yardım merkezi kapanır (yalnız üretici belge makalelerini açıyordu), kurulum rehberi ve kenar
# çubuğunun sabit İngilizce metinleri Türkçe. Aynı dosyaya iki ayrı yama çakışır: hepsi tek yama dosyasında.
APPENDS: list[tuple[str, Path]] = [
	("helpdesk/desk/patches/frappe-ui+1.0.0-beta.24.patch", MARKA / "yamalar" / "frappe-ui-nanobase.patch"),
]

COPIES: list[tuple[Path, str]] = [
	(MARKA / "favicon.svg", "helpdesk/desk/public/favicon.svg"),
]

# Kullanılmayan ya da üretici markası taşıyan medya
REMOVE = [
	"helpdesk/desk/public/videos/commentVideo.mp4",
	"helpdesk/desk/public/videos/mailVideo.mp4",
	"helpdesk/desk/public/videos/sidebarVideo.mp4",
]

# Denetim: bu desenler ekrana çıkan dosyalarda kalmamalı.
AUDIT_PATTERNS = [r"https?://(?!localhost|www\.w3\.org|flagcdn\.com|fonts\.googleapis\.com|fonts\.gstatic\.com|posta\.ornek)[a-z0-9.-]+\.[a-z]{2,}", r"Frappe Helpdesk", r"\bTeam Frappe\b", r'"Helpdesk"', r"t\.me/frappedesk", r"Frappe Cloud\b(?!Icon)"]
# Ekrana çıkmayan satırlar: önbellek anahtarı ve menüden kaldırılan bulut girişinin ölü kodu.
AUDIT_SKIP = [r"cache: \[", r"composables/fc\.ts", r"^[^:]*:\d+:\s*(\*|//)", r"xmlns="]
AUDIT_GLOBS = ["helpdesk/desk/src/**/*.vue", "helpdesk/desk/src/**/*.ts", "helpdesk/desk/index.html", "flow/frontend/src/**/*.vue"]


def apply() -> int:
	problems: list[str] = []
	for rel, pairs in EDITS:
		path = APPS / rel
		text = path.read_text()
		for old, new in pairs:
			# Önce yeni metne bak: yeni metin eskisini içerebilir (ekleme), ikinci koşu tekrar eklemesin.
			if new and new in text:
				continue
			if old in text:
				text = text.replace(old, new)
			elif not new:
				# Silme: yeni metin boş; eski yoksa zaten silinmiştir ya da üst kaynak değişmiştir.
				# Bloğun ilk yarısı duruyor ama tamamı yoksa üst kaynak bloğu değiştirmiştir.
				head = old[: max(len(old) // 2, 1)]
				if head.strip() and head in text:
					problems.append(f"{rel}: silinecek blok değişmiş: {head.strip().splitlines()[0][:80]}")
			else:
				problems.append(f"{rel}: bulunamadı: {old[:80]!r}")
		path.write_text(text)
	for rel, pattern, new in BLOCKS:
		path = APPS / rel
		text = path.read_text()
		updated, n = re.subn(pattern, lambda _m: new, text, count=1, flags=re.S)
		if n == 0 and new not in text:
			problems.append(f"{rel}: blok deseni bulunamadı: {pattern}")
		path.write_text(updated)
	for rel, content in WRITES:
		(APPS / rel).write_text(content)
	for rel, src in APPENDS:
		path = APPS / rel
		if not path.exists():
			problems.append(f"{rel}: yama dosyası yok (frappe-ui sürümü değişmiş olabilir)")
			continue
		text, extra = path.read_text(), src.read_text()
		if extra not in text:
			path.write_text(text.rstrip("\n") + "\n" + extra)
	for src, rel in COPIES:
		shutil.copyfile(src, APPS / rel)
	for rel in REMOVE:
		(APPS / rel).unlink(missing_ok=True)
	for p in problems:
		print("SORUN", p)
	return 1 if problems else 0


def audit() -> int:
	hits = 0
	for pattern in AUDIT_GLOBS:
		for path in sorted(APPS.glob(pattern)):
			for n, line in enumerate(path.read_text(errors="ignore").splitlines(), 1):
				where = f"{path.relative_to(APPS)}:{n}: {line}"
				if any(re.search(rx, where) for rx in AUDIT_SKIP):
					continue
				for rx in AUDIT_PATTERNS:
					if re.search(rx, line):
						hits += 1
						print(f"{path.relative_to(APPS)}:{n}: {line.strip()[:120]}")
	print(f"kalan marka izi: {hits}")
	return 1 if hits else 0


if __name__ == "__main__":
	sys.exit(audit() if "--denetle" in sys.argv else apply())
